export {
  CONFIDENCE_SYSTEM_ENGINE_VERSION,
  CONFIDENCE_SYSTEM_HONESTY,
  CONFIDENCE_DISPLAY_LABELS,
  CONFIDENCE_PERCENTAGES_CALIBRATED,
  CONFIDENCE_BADGE_VARIANT,
  UNIVERSAL_CONFIDENCE_LEVELS,
  UNIVERSAL_CONFIDENCE_LABELS,
  normalizeConfidenceLevel,
  toUniversalConfidence,
  formatConfidenceLabel,
  confidenceBadgeVariant,
  isConfidenceDisplayable,
  formatConfidencePercent,
  formatConfidenceWithOptionalPercent,
  type UniversalConfidenceLevel,
  type StoredConfidenceLevel,
  type ConfidenceBadgeVariant,
} from "@/domain/confidence-system/constants";
