export {
  scoreProgramFinder,
  familyHasFreeTrial,
  freeProductSlugForFamily,
  paidProductSlugForFamily,
  programFinderFamilyLabel,
  PROGRAM_FINDER_FAMILIES,
  PROGRAM_FINDER_GOALS,
  PROGRAM_FINDER_EXPERIENCE,
  PROGRAM_FINDER_DAYS,
  PROGRAM_FINDER_WEAKEST,
  PROGRAM_FINDER_RECOVERY,
  type ProgramFinderAnswers,
  type ProgramFinderFamilyId,
  type ProgramFinderResult,
  type ProgramFinderScoreBreakdown,
} from "@/domain/program-finder/scoring";
