import { featureFlags, type FeatureFlagKey } from "@/config/feature-flags";

export type RouteAudience = "public" | "authenticated";

export type AppRoute = {
  /** Stable route id */
  id: string;
  /** Path pattern (no trailing slash except home) */
  href: string;
  /** Nav label */
  label: string;
  audience: RouteAudience;
  /** Shown in primary navigation when true and flag allows */
  nav: boolean;
  /** Optional feature flag; when set and false, hide from nav and gate the page */
  flag?: FeatureFlagKey;
  /** Whether a page file exists in this prompt */
  implemented: boolean;
  description: string;
};

/**
 * Canonical route architecture for The Strongest.
 * Keep this file as the source of truth for nav + IA docs.
 */
export const routes: readonly AppRoute[] = [
  // —— Public ——
  {
    id: "home",
    href: "/",
    label: "Home",
    audience: "public",
    nav: true,
    implemented: true,
    description: "Marketing home — brand entry and primary signup CTA.",
  },
  {
    id: "search",
    href: "/search",
    label: "Search",
    audience: "public",
    nav: false,
    implemented: true,
    description:
      "Mobile/full-page global search (exercises, methods, articles, academy). Desktop uses command palette.",
  },
  {
    id: "features",
    href: "/features",
    label: "Features",
    audience: "public",
    nav: true,
    implemented: true,
    description: "Product capability overview without fake metrics or claims.",
  },
  {
    id: "demo",
    href: "/demo",
    label: "Demo",
    audience: "public",
    nav: true,
    flag: "demoMode",
    implemented: true,
    description:
      "Explicit Demo Mode with labeled example athlete data for sales and screenshots.",
  },
  {
    id: "exercises",
    href: "/exercises",
    label: "Exercises",
    audience: "public",
    nav: true,
    implemented: true,
    description: "Public exercise intelligence index (priority catalog).",
  },
  {
    id: "exercise-detail",
    href: "/exercises/[slug]",
    label: "Exercise detail",
    audience: "public",
    nav: false,
    implemented: true,
    description: "Single exercise intelligence page from the published catalog.",
  },
  {
    id: "methods",
    href: "/methods",
    label: "Training Methods",
    audience: "public",
    nav: true,
    implemented: true,
    description:
      "Public training-methods catalog with historical and modern coaching context.",
  },
  {
    id: "method-detail",
    href: "/methods/[slug]",
    label: "Method detail",
    audience: "public",
    nav: false,
    flag: "methodDetail",
    implemented: true,
    description:
      "Single training-method page: origins, principles, use cases, limitations, modern interpretation.",
  },
  {
    id: "compare",
    href: "/compare",
    label: "Compare",
    audience: "public",
    nav: false,
    flag: "compare",
    implemented: true,
    description:
      "Compare 2–3 training methods with qualitative dimensions and shareable URLs.",
  },
  {
    id: "compare-exercises",
    href: "/compare/exercises",
    label: "Compare exercises",
    audience: "public",
    nav: false,
    flag: "exerciseComparison",
    implemented: true,
    description:
      "Exercise A vs B — purpose, technique, muscles, fatigue, programming, who should choose.",
  },
  {
    id: "compare-exercises-slug",
    href: "/compare/exercises/[slug]",
    label: "Exercise comparison guide",
    audience: "public",
    nav: false,
    flag: "exerciseComparison",
    implemented: true,
    description:
      "SEO allowlisted exercise comparison pair (Article + FAQ when present).",
  },
  {
    id: "goals",
    href: "/goals",
    label: "Goals",
    audience: "public",
    nav: false,
    flag: "sportGoalLandings",
    implemented: true,
    description:
      "Sport/goal landing hub — product CTAs, no generic SEO filler.",
  },
  {
    id: "goals-slug",
    href: "/goals/[slug]",
    label: "Goal landing",
    audience: "public",
    nav: false,
    flag: "sportGoalLandings",
    implemented: true,
    description:
      "Allowlisted sport/goal landing with links into real product features.",
  },
  {
    id: "tools",
    href: "/tools",
    label: "Tools",
    audience: "public",
    nav: false,
    flag: "calculatorSuite",
    implemented: true,
    description:
      "Calculator suite hub — 1RM, plates, DOTS, volume, attempts, training max.",
  },
  {
    id: "tools-slug",
    href: "/tools/[slug]",
    label: "Calculator",
    audience: "public",
    nav: false,
    flag: "calculatorSuite",
    implemented: true,
    description:
      "Allowlisted training calculator with precision honesty and product CTAs.",
  },
  {
    id: "technique-check",
    href: "/technique-check",
    label: "Free technique check",
    audience: "public",
    nav: false,
    flag: "techniqueCheck",
    implemented: true,
    description:
      "Upload one lift → limited insight before signup; guest video stays local.",
  },
  {
    id: "program-audit",
    href: "/program-audit",
    label: "Free program audit",
    audience: "public",
    nav: false,
    flag: "programAudit",
    implemented: true,
    description:
      "Paste program → deterministic basic audit; unlock details with account. No fake scores.",
  },
  {
    id: "athlete-assessment",
    href: "/athlete-assessment",
    label: "Free athlete assessment",
    audience: "public",
    nav: false,
    flag: "athleteAssessment",
    implemented: true,
    description:
      "Limited questions → Self-assessment estimate — Not full Athlete Score.",
  },
  {
    id: "history",
    href: "/history",
    label: "History",
    audience: "public",
    nav: false,
    flag: "history",
    implemented: true,
    description:
      "Educational timeline: evolution of strength and physique training with links to method pages.",
  },
  {
    id: "history-era",
    href: "/history/[slug]",
    label: "History era",
    audience: "public",
    nav: false,
    flag: "history",
    implemented: true,
    description: "Single era page within the training history timeline.",
  },
  {
    id: "history-archive",
    href: "/history/archive",
    label: "History archive",
    audience: "public",
    nav: false,
    flag: "historicalTrainingArchive",
    implemented: true,
    description:
      "Historical Training Archive: systems, coaches, famous methods — principles only with three analytical lenses.",
  },
  {
    id: "history-archive-profile",
    href: "/history/archive/[slug]",
    label: "History archive profile",
    audience: "public",
    nav: false,
    flag: "historicalTrainingArchive",
    implemented: true,
    description: "Single archive profile within the Historical Training Archive.",
  },
  {
    id: "evidence",
    href: "/evidence",
    label: "Evidence",
    audience: "public",
    nav: false,
    flag: "evidenceQualitySystem",
    implemented: true,
    description:
      "Evidence Quality System legend: research vs expert practice labels — no fake certainty.",
  },
  {
    id: "research",
    href: "/research",
    label: "Research",
    audience: "public",
    nav: false,
    flag: "researchLibrary",
    implemented: true,
    description:
      "Research Library: curated study entries by category — real citations only.",
  },
  {
    id: "research-entry",
    href: "/research/[slug]",
    label: "Research entry",
    audience: "public",
    nav: false,
    flag: "researchLibrary",
    implemented: true,
    description: "Single Research Library entry.",
  },
  {
    id: "admin-research-summarizer",
    href: "/app/admin/research/summarizer",
    label: "AI Research Summarizer",
    audience: "authenticated",
    nav: false,
    flag: "aiResearchSummarizer",
    implemented: true,
    description:
      "AI drafts from verified paper metadata/text — human review before public publication; never invents citations.",
  },
  {
    id: "myths",
    href: "/myths",
    label: "Myth vs Reality",
    audience: "public",
    nav: false,
    flag: "mythVsRealityEngine",
    implemented: true,
    description:
      "Myth vs Reality Engine: claim, what people say, evidence, practical answer, nuance — no clickbait misinformation.",
  },
  {
    id: "myth-entry",
    href: "/myths/[slug]",
    label: "Myth page",
    audience: "public",
    nav: false,
    flag: "mythVsRealityEngine",
    implemented: true,
    description: "Single Myth vs Reality educational page.",
  },
  {
    id: "decision-trees",
    href: "/decision-trees",
    label: "Decision trees",
    audience: "public",
    nav: false,
    flag: "decisionTreeCoaching",
    implemented: true,
    description:
      "Decision Tree Coaching Tools: interactive structured rules with explained outputs — not medical advice.",
  },
  {
    id: "decision-tree",
    href: "/decision-trees/[slug]",
    label: "Decision tree",
    audience: "public",
    nav: false,
    flag: "decisionTreeCoaching",
    implemented: true,
    description: "Single interactive coaching decision tree.",
  },
  {
    id: "fit",
    href: "/fit",
    label: "Fit",
    audience: "public",
    nav: false,
    flag: "fit",
    implemented: true,
    description:
      "What training approach fits me? Transparent rule-based primary + alternative recommendations.",
  },
  {
    id: "pr-share",
    href: "/share/pr/[token]",
    label: "PR share",
    audience: "public",
    nav: false,
    flag: "prIntelligence",
    implemented: true,
    description: "Public personal-record celebration card (opaque token, noindex).",
  },
  {
    id: "technique-share",
    href: "/share/technique/[token]",
    label: "Technique share",
    audience: "public",
    nav: false,
    implemented: true,
    description:
      "Public technique score card with Analyze your lift CTA and referral UTMs.",
  },
  {
    id: "public-athlete",
    href: "/u/[slug]",
    label: "Public athlete",
    audience: "public",
    nav: false,
    flag: "publicAthleteProfile",
    implemented: true,
    description:
      "Optional public athlete profile — private by default; custom slug.",
  },
  {
    id: "learn",
    href: "/learn",
    label: "Learn",
    audience: "public",
    nav: true,
    implemented: true,
    description:
      "SEO topic clusters — pillars with meaningful content; supporting links to deep pages only.",
  },
  {
    id: "learn-cluster",
    href: "/learn/[slug]",
    label: "Learn topic",
    audience: "public",
    nav: false,
    implemented: true,
    description: "Topic pillar page (Article + Breadcrumb + FAQ when valid).",
  },
  {
    id: "guides",
    href: "/guides",
    label: "Guides",
    audience: "public",
    nav: false,
    flag: "programmaticSeoSafety",
    implemented: true,
    description:
      "Quality-gated programmatic SEO guide hub — no thin page factories.",
  },
  {
    id: "guides-slug",
    href: "/guides/[slug]",
    label: "Guide",
    audience: "public",
    nav: false,
    flag: "programmaticSeoSafety",
    implemented: true,
    description:
      "Allowlisted guide page (unique value, schema, links, quality gates).",
  },
  {
    id: "coaching",
    href: "/coaching",
    label: "Coaching",
    audience: "public",
    nav: true,
    flag: "coachMarketplace",
    implemented: true,
    description:
      "Coach marketplace MVP — browse, filter by sport, view profile, request consultation (no payments).",
  },
  {
    id: "coaching-match",
    href: "/coaching/match",
    label: "Find a coach",
    audience: "public",
    nav: true,
    flag: "coachMatching",
    implemented: true,
    description:
      "Coach matching by goal, sport, experience, budget, language, location, style — organic rank; sponsored labeled.",
  },
  {
    id: "academy",
    href: "/academy",
    label: "Academy",
    audience: "public",
    nav: false,
    implemented: true,
    description:
      "Academy landing + course catalog (Certificate of Completion only).",
  },
  {
    id: "academy-course",
    href: "/academy/[slug]",
    label: "Academy course",
    audience: "public",
    nav: false,
    implemented: true,
    description: "Public course detail (modules, lessons, quiz outline).",
  },
  {
    id: "verify-certificate",
    href: "/verify/certificate",
    label: "Verify certificate",
    audience: "public",
    nav: false,
    flag: "certificateVerification",
    implemented: true,
    description:
      "Public Certificate of Completion verification — unique ID, name, course, date, status; never accredited by default.",
  },
  {
    id: "verify-certificate-code",
    href: "/verify/certificate/[code]",
    label: "Verify certificate result",
    audience: "public",
    nav: false,
    flag: "certificateVerification",
    implemented: true,
    description: "Verification result for a unique certificate ID.",
  },
  {
    id: "pricing",
    href: "/pricing",
    label: "Pricing",
    audience: "public",
    nav: true,
    implemented: true,
    description:
      "Plans: Free, Pro, Performance, optional Elite — catalog prices, limits, cancellation.",
  },
  {
    id: "privacy",
    href: "/privacy",
    label: "Privacy",
    audience: "public",
    nav: false,
    implemented: true,
    description:
      "Privacy Policy draft — for professional legal review (not counsel-approved).",
  },
  {
    id: "cookies",
    href: "/cookies",
    label: "Cookies",
    audience: "public",
    nav: false,
    flag: "gdprReadiness",
    implemented: true,
    description:
      "Cookie Policy + preference controls — draft for professional legal review.",
  },
  {
    id: "terms",
    href: "/terms",
    label: "Terms",
    audience: "public",
    nav: false,
    implemented: true,
    description:
      "Terms of Use draft — for professional legal review (not counsel-approved).",
  },
  {
    id: "trust-center",
    href: "/trust",
    label: "Trust Center",
    audience: "public",
    nav: false,
    flag: "trustCenter",
    implemented: true,
    description:
      "Public Trust Center — how AI works, limits, data/video privacy, scoring, safety, evidence.",
  },

  // —— Authenticated Performance OS ——
  {
    id: "app-root",
    href: "/app",
    label: "App",
    audience: "authenticated",
    nav: false,
    implemented: true,
    description: "Authenticated root; redirects to dashboard.",
  },
  {
    id: "dashboard",
    href: "/app/dashboard",
    label: "Dashboard",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Command Center when flagged: TODAY above fold, customizable widgets; honest empty states.",
  },
  {
    id: "profile",
    href: "/app/profile",
    label: "Profile",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description: "Persistent athlete profile with editable training identity.",
  },
  {
    id: "today",
    href: "/app/today",
    label: "Today",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Daily coaching brief and today’s session — the central next-action surface.",
  },
  {
    id: "training",
    href: "/app/training",
    label: "Training",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description: "Active training workspace — resumes in-progress workouts.",
  },
  {
    id: "training-session",
    href: "/app/training/[sessionId]",
    label: "Workout session",
    audience: "authenticated",
    nav: false,
    implemented: true,
    description:
      "Live workout player: mobile-first one-exercise focus, large steppers, auto-save, rest timer, previous performance.",
  },
  {
    id: "programs",
    href: "/app/programs",
    label: "Programs",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description: "Program library, assignments, and adaptive suggestions.",
  },
  {
    id: "program-builder",
    href: "/app/program-builder",
    label: "Program Builder",
    audience: "authenticated",
    nav: true,
    flag: "programBuilder",
    implemented: true,
    description:
      "Program Builder 2.0: structured drafts from goal, days, session, equipment, priority lifts, experience — editable, no random AI volume.",
  },
  {
    id: "program-versions",
    href: "/app/programs/[id]/versions",
    label: "Program versions",
    audience: "authenticated",
    nav: false,
    flag: "programVersionControl",
    implemented: true,
    description:
      "Program Version Control: v1/v2/v3 history with who/why/date, restore, completed training protected.",
  },
  {
    id: "experiments",
    href: "/app/experiments",
    label: "Experiments",
    audience: "authenticated",
    nav: true,
    flag: "experimentMode",
    implemented: true,
    description:
      "Experiment Mode: personal training experiments with hypothesis, measures, and before/after — not scientific research.",
  },
  {
    id: "experiment-detail",
    href: "/app/experiments/[id]",
    label: "Experiment detail",
    audience: "authenticated",
    nav: false,
    flag: "experimentMode",
    implemented: true,
    description: "Single personal training experiment with before/after compare.",
  },
  {
    id: "programming-insights",
    href: "/app/programming-insights",
    label: "Programming insights",
    audience: "authenticated",
    nav: true,
    flag: "abProgrammingInsights",
    implemented: true,
    description:
      "A/B Programming Insights: anonymized aggregate architecture with sample thresholds — correlation ≠ causation.",
  },
  {
    id: "bodyweight-performance",
    href: "/app/bodyweight-performance",
    label: "Bodyweight & performance",
    audience: "authenticated",
    nav: true,
    flag: "bodyweightPerformance",
    implemented: true,
    description:
      "Bodyweight / Performance Relationship: BW, estimated strength, relative strength trends — weight gain ≠ automatic strength.",
  },
  {
    id: "recovery-correlation",
    href: "/app/recovery-correlation",
    label: "Recovery correlations",
    audience: "authenticated",
    nav: true,
    flag: "recoveryCorrelation",
    implemented: true,
    description:
      "Recovery Correlation Insights: sleep / stress / soreness vs performance — observed association, sample-gated, not causal proof.",
  },
  {
    id: "training-consistency",
    href: "/app/training-consistency",
    label: "Training consistency",
    audience: "authenticated",
    nav: true,
    flag: "trainingConsistencyIntelligence",
    implemented: true,
    description:
      "Training Consistency Intelligence: plan adherence (rest, deload, injury, program change) — not days in the gym.",
  },
  {
    id: "deload-intelligence",
    href: "/app/deload-intelligence",
    label: "Deload intelligence",
    audience: "authenticated",
    nav: true,
    flag: "deloadIntelligence",
    implemented: true,
    description:
      "Deload Intelligence: multi-signal Consider deload — never from one workout; user decides; never auto-applied.",
  },
  {
    id: "fatigue-alerts",
    href: "/app/fatigue-alerts",
    label: "Fatigue alerts",
    audience: "authenticated",
    nav: true,
    flag: "fatigueAlertSystem",
    implemented: true,
    description:
      "Fatigue Alert System: Normal / Watch / Elevated / High concern — load, performance, recovery; no medical claims.",
  },
  {
    id: "pain-safe-response",
    href: "/app/pain-safe-response",
    label: "Pain-safe response",
    audience: "authenticated",
    nav: true,
    flag: "painSafeResponseSystem",
    implemented: true,
    description:
      "Pain-Safe Response System: sharp pain / neuro / serious injury — stop aggressive recs; seek medical evaluation; never diagnose.",
  },
  {
    id: "exercise-substitutions",
    href: "/app/exercise-substitutions",
    label: "Exercise substitutions",
    audience: "authenticated",
    nav: true,
    flag: "exerciseSubstitutions",
    implemented: true,
    description:
      "Smart Exercise Substitutions: replacements by goal, pattern, fatigue, and skill — with tradeoffs.",
  },
  {
    id: "equipment-profiles",
    href: "/app/equipment-profiles",
    label: "Equipment profiles",
    audience: "authenticated",
    nav: true,
    flag: "equipmentAwareProgramming",
    implemented: true,
    description:
      "Equipment-Aware Programming: commercial / home / powerlifting / minimal profiles — suggestions respect gear.",
  },
  {
    id: "travel-mode",
    href: "/app/travel-mode",
    label: "Travel Mode",
    audience: "authenticated",
    nav: true,
    flag: "travelTrainingMode",
    implemented: true,
    description:
      "Travel Training Mode: hotel gym / no gym / limited — temporary adaptation; original program preserved.",
  },
  {
    id: "injury-modification",
    href: "/app/injury-modification",
    label: "Injury modification",
    audience: "authenticated",
    nav: true,
    flag: "injuryModification",
    implemented: true,
    description:
      "Injury-Modification Architecture: user-declared limitations (not diagnosis) — alternatives, reduced range, lower loading.",
  },
  {
    id: "coaching-notes",
    href: "/app/coaching-notes",
    label: "Coaching notes",
    audience: "authenticated",
    nav: true,
    flag: "coachingNotesIntelligence",
    implemented: true,
    description:
      "Coaching Notes Intelligence: coach notes + AI summaries with source labels; private notes stay out of unrelated product use.",
  },
  {
    id: "messages",
    href: "/app/messages",
    label: "Messages",
    audience: "authenticated",
    nav: true,
    flag: "messagingSystem",
    implemented: true,
    description:
      "Athlete–coach messaging: threads, attachments, workout/technique refs, notifications, moderation, secure access.",
  },
  {
    id: "check-in",
    href: "/app/check-in",
    label: "Weekly check-in",
    audience: "authenticated",
    nav: true,
    flag: "checkInSystem",
    implemented: true,
    description:
      "Customizable weekly check-in: training, recovery, bodyweight, goals — coach configures; AI summarizes.",
  },
  {
    id: "check-in-configure",
    href: "/app/check-in/configure",
    label: "Configure check-in",
    audience: "authenticated",
    nav: false,
    flag: "checkInSystem",
    implemented: true,
    description: "Coach configures allowlisted weekly check-in questions.",
  },
  {
    id: "premium-coaching-landing",
    href: "/coaching/premium",
    label: "Premium coaching",
    audience: "public",
    nav: false,
    flag: "premiumCoachingSales",
    implemented: true,
    description:
      "Premium coaching sales landing — apply funnel; never promises acceptance.",
  },
  {
    id: "premium-coaching-apply",
    href: "/coaching/premium/apply",
    label: "Apply for premium coaching",
    audience: "public",
    nav: false,
    flag: "premiumCoachingSales",
    implemented: true,
    description: "Premium coaching application form.",
  },
  {
    id: "premium-coaching-status",
    href: "/app/premium-coaching",
    label: "Premium applications",
    audience: "authenticated",
    nav: true,
    flag: "premiumCoachingSales",
    implemented: true,
    description: "Athlete premium coaching application status.",
  },
  {
    id: "premium-coaching-review",
    href: "/app/premium-coaching/review",
    label: "Review premium apps",
    audience: "authenticated",
    nav: true,
    flag: "premiumCoachingSales",
    implemented: true,
    description: "Staff/coach review: Advance Apply → Review → Consultation → Offer.",
  },
  {
    id: "referral-program",
    href: "/app/referral",
    label: "Referrals",
    audience: "authenticated",
    nav: true,
    flag: "referralProgram",
    implemented: true,
    description:
      "Personal referral code + single-level rewards (credits / complimentary access). No pyramid.",
  },
  {
    id: "affiliate-hub",
    href: "/app/affiliate",
    label: "Affiliates",
    audience: "authenticated",
    nav: true,
    flag: "affiliateSystem",
    implemented: true,
    description:
      "Creator/coach/partner affiliate hub — clicks, conversions, commission ledger; disclosure required.",
  },
  {
    id: "affiliate-review",
    href: "/app/affiliate/review",
    label: "Review affiliates",
    audience: "authenticated",
    nav: true,
    flag: "affiliateSystem",
    implemented: true,
    description: "Staff activate affiliate partners.",
  },
  {
    id: "affiliates-directory",
    href: "/affiliates",
    label: "Affiliate partners",
    audience: "public",
    nav: false,
    flag: "affiliateSystem",
    implemented: true,
    description:
      "Public affiliate directory — never shown without disclosure.",
  },
  {
    id: "creator-program",
    href: "/app/creator",
    label: "Creator Program",
    audience: "authenticated",
    nav: true,
    flag: "creatorProgram",
    implemented: true,
    description:
      "Creator partnership application — capabilities unlock only after approval.",
  },
  {
    id: "creator-review",
    href: "/app/creator/review",
    label: "Review creators",
    audience: "authenticated",
    nav: true,
    flag: "creatorProgram",
    implemented: true,
    description: "Staff approve/reject/suspend creator applications.",
  },
  {
    id: "program-marketplace-browse",
    href: "/programs/marketplace",
    label: "Program marketplace",
    audience: "public",
    nav: false,
    flag: "programMarketplace",
    implemented: true,
    description:
      "Public training program marketplace — verified-purchaser ratings only.",
  },
  {
    id: "program-marketplace-hub",
    href: "/app/program-marketplace",
    label: "Sell programs",
    audience: "authenticated",
    nav: true,
    flag: "programMarketplace",
    implemented: true,
    description:
      "Creator publish hub for program listings (requires Creator Program approval).",
  },
  {
    id: "program-marketplace-review",
    href: "/app/program-marketplace/review",
    label: "Review programs",
    audience: "authenticated",
    nav: true,
    flag: "programMarketplace",
    implemented: true,
    description: "Staff copyright review for program marketplace listings.",
  },
  {
    id: "content-moderation",
    href: "/app/moderation",
    label: "Moderation",
    audience: "authenticated",
    nav: true,
    flag: "contentModeration",
    implemented: true,
    description:
      "Staff content moderation queue — report, review, remove, suspend, audit log.",
  },
  {
    id: "program-review",
    href: "/app/program-review",
    label: "Program review",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "AI-assisted program analysis: volume, intensity, balance, goal fit — contextual, never auto-applied.",
  },
  {
    id: "training-audit",
    href: "/app/training-audit",
    label: "Training audit",
    audience: "authenticated",
    nav: true,
    flag: "trainingAudit",
    implemented: true,
    description:
      "Upload → analyze → understand → improve. CSV, paste, or manual entry — never fabricates program details.",
  },
  {
    id: "exercise-prescription",
    href: "/app/exercise-prescription",
    label: "Exercise picks",
    audience: "authenticated",
    nav: true,
    flag: "exercisePrescription",
    implemented: true,
    description:
      "Multi-rule exercise recommendations: reason, purpose, fatigue, skill, placement, alternatives.",
  },
  {
    id: "weak-points",
    href: "/app/weak-points",
    label: "Weak points",
    audience: "authenticated",
    nav: true,
    flag: "weakPointIntelligence",
    implemented: true,
    description:
      "Evidence-backed weak-point findings with confidence and validation — never from appearance alone.",
  },
  {
    id: "pr-prediction",
    href: "/app/pr-prediction",
    label: "PR prediction",
    audience: "authenticated",
    nav: true,
    flag: "prPrediction",
    implemented: true,
    description:
      "Conservative estimated 1RM ranges from working sets, RPE, trend, phase, and fatigue — never a single exact number.",
  },
  {
    id: "goal-progress",
    href: "/app/goal-progress",
    label: "Goal progress",
    audience: "authenticated",
    nav: true,
    flag: "goalProbability",
    implemented: true,
    description:
      "Goal trajectory vs deadline: current estimate, required improvement, time left — qualitative status only, never a fake probability %.",
  },
  {
    id: "competition",
    href: "/app/competition",
    label: "Competition",
    audience: "authenticated",
    nav: true,
    flag: "competitionMode",
    implemented: true,
    description:
      "Competition Mode: countdown, phase, taper sketches, attempts, bodyweight, readiness — never an automatic weight-cut protocol.",
  },
  {
    id: "live-competition",
    href: "/app/competition/live",
    label: "Live Competition",
    audience: "authenticated",
    nav: false,
    flag: "liveCompetitionMode",
    implemented: true,
    description:
      "Meet-day architecture — attempts, results, next attempt, warm-up timing, offline; runtime gated; no unsafe instructions.",
  },
  {
    id: "attempt-selector",
    href: "/app/attempt-selector",
    label: "Attempt selector",
    audience: "authenticated",
    nav: true,
    flag: "attemptSelector",
    implemented: true,
    description:
      "Powerlifting attempt planning: opener, second, conditional third with risk preference — never a guaranteed make.",
  },
  {
    id: "warmup-generator",
    href: "/app/warmup",
    label: "Warm-ups",
    audience: "authenticated",
    nav: true,
    flag: "warmupGenerator",
    implemented: true,
    description:
      "Progressive warm-up planner from target working weight, exercise, and recent history — conservative, editable, fatigue-aware.",
  },
  {
    id: "session-readiness",
    href: "/app/session-readiness",
    label: "Session readiness",
    audience: "authenticated",
    nav: true,
    flag: "sessionReadinessAdjuster",
    implemented: true,
    description:
      "Pre-workout check-in: sleep, fatigue, soreness, motivation — proceed / minor adjustment / review load; never cancel from one metric.",
  },
  {
    id: "powerlifting",
    href: "/app/powerlifting",
    label: "Powerlifting",
    audience: "authenticated",
    nav: true,
    flag: "powerliftingMode",
    implemented: true,
    description:
      "Powerlifting Mode: SBD, total, competition, weight class, attempts — DOTS via /tools/dots; Wilks/IPF GL deferred; federation later.",
  },
  {
    id: "bodybuilding",
    href: "/app/bodybuilding",
    label: "Bodybuilding",
    audience: "authenticated",
    nav: true,
    flag: "bodybuildingMode",
    implemented: true,
    description:
      "Bodybuilding Mode: muscle groups, weekly volume, progression, bodyweight — no fake growth scores; photos private.",
  },
  {
    id: "strongman",
    href: "/app/strongman",
    label: "Strongman",
    audience: "authenticated",
    nav: true,
    flag: "strongmanMode",
    implemented: true,
    description:
      "Strongman Mode: log, axle, farmer’s, yoke, stones, deadlift variations — event PRs; no forced powerlifting metrics.",
  },
  {
    id: "weightlifting",
    href: "/app/weightlifting",
    label: "Weightlifting",
    audience: "authenticated",
    nav: true,
    flag: "weightliftingMode",
    implemented: true,
    description:
      "Weightlifting Mode: snatch, clean, jerk, C&J — technique analysis deferred; advanced video flagged off by default.",
  },
  {
    id: "multi-sport",
    href: "/app/multi-sport",
    label: "Multi-Sport",
    audience: "authenticated",
    nav: true,
    flag: "multiSportAthleteMode",
    implemented: true,
    description:
      "Multi-Sport Athlete Mode: multiple focuses on one profile; PRs separated by sport; mixed goals allowed.",
  },
  {
    id: "exercise-graph",
    href: "/app/exercise-graph",
    label: "Exercise Graph",
    audience: "authenticated",
    nav: true,
    flag: "exerciseRelationshipGraph",
    implemented: true,
    description:
      "Exercise Relationship Graph: curated variation/muscle/weak-point/sport/method/technique edges — no arbitrary links.",
  },
  {
    id: "method-graph",
    href: "/app/method-graph",
    label: "Method Graph",
    audience: "authenticated",
    nav: true,
    flag: "trainingMethodKnowledgeGraph",
    implemented: true,
    description:
      "Training Method Knowledge Graph: methods, coaches, sports, goals, volume/intensity/recovery — interactive exploration.",
  },
  {
    id: "adaptations",
    href: "/app/adaptations",
    label: "Adaptations",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Review adaptive programming suggestions — Accept, Modify, or Decline.",
  },
  {
    id: "program-detail",
    href: "/app/programs/[id]",
    label: "Program detail",
    audience: "authenticated",
    nav: false,
    flag: "programDetail",
    implemented: true,
    description: "Single program view (flagged until programming engine ships).",
  },
  {
    id: "app-exercises",
    href: "/app/exercises",
    label: "Exercises",
    audience: "authenticated",
    nav: true,
    flag: "appExercises",
    implemented: true,
    description: "In-app exercise intelligence browser.",
  },
  {
    id: "technique",
    href: "/app/technique",
    label: "Technique",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description: "Technique analysis hub.",
  },
  {
    id: "technique-trends",
    href: "/app/technique-trends",
    label: "Technique trends",
    audience: "authenticated",
    nav: true,
    flag: "techniqueTrendEngine",
    implemented: true,
    description:
      "Longitudinal Technique Score series: improved / stable / regressed metrics on compatible camera angles.",
  },
  {
    id: "technique-compare",
    href: "/app/technique/compare",
    label: "Compare lifts",
    audience: "authenticated",
    nav: true,
    flag: "videoComparison",
    implemented: true,
    description:
      "Side-by-side old vs new lift: synced playback, frame step, speed, overlay, landmarks.",
  },
  {
    id: "technique-analysis",
    href: "/app/technique/[analysisId]",
    label: "Technique analysis",
    audience: "authenticated",
    nav: false,
    implemented: true,
    description:
      "Premium technique report: score, video timeline, prioritized actions, comparison.",
  },
  {
    id: "technique-diagnostics",
    href: "/app/technique/[analysisId]/diagnostics",
    label: "Movement diagnostics",
    audience: "authenticated",
    nav: false,
    implemented: true,
    description: "Developer diagnostics for pose/movement pipeline.",
  },
  {
    id: "progress",
    href: "/app/progress",
    label: "Progress",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Progress analytics: strength, PRs, e1RM, volume, bodyweight, technique, consistency, adherence.",
  },
  {
    id: "timeline",
    href: "/app/timeline",
    label: "Timeline",
    audience: "authenticated",
    nav: true,
    flag: "universalTimeline",
    implemented: true,
    description:
      "Universal athlete history — workouts, PRs, technique, programs, competition, bodyweight, coach notes; filters.",
  },
  {
    id: "performance-story",
    href: "/app/performance-story",
    label: "Story",
    audience: "authenticated",
    nav: true,
    flag: "performanceStory",
    implemented: true,
    description:
      "Performance Story — long-term yearly narrative from logged history; shareable; no fake causation.",
  },
  {
    id: "year-in-review",
    href: "/app/year-in-review",
    label: "Year in Review",
    audience: "authenticated",
    nav: true,
    flag: "yearInReview",
    implemented: true,
    description:
      "Annual Iron Almanac — sessions, PRs, technique, top exercises, consistency, competition; shareable cards.",
  },
  {
    id: "year-in-review-share",
    href: "/share/year/[token]",
    label: "Year in Review share",
    audience: "public",
    nav: false,
    flag: "yearInReview",
    implemented: true,
    description: "Public-safe Year in Review card deck.",
  },
  {
    id: "activity-feed",
    href: "/app/activity-feed",
    label: "Activity feed",
    audience: "authenticated",
    nav: false,
    flag: "activityFeedMvp",
    implemented: true,
    description:
      "Optional finite milestones — PRs, competition, achievements, shared technique; visibility controls; no endless engagement.",
  },
  {
    id: "performance-story-share",
    href: "/share/story/[token]",
    label: "Performance Story share",
    audience: "public",
    nav: false,
    flag: "performanceStory",
    implemented: true,
    description: "Public-safe yearly Performance Story review card.",
  },
  {
    id: "prs",
    href: "/app/prs",
    label: "PRs",
    audience: "authenticated",
    nav: true,
    flag: "prIntelligence",
    implemented: true,
    description:
      "Personal Record Intelligence: 1RM, estimated 1RM, rep, volume, technical PRs — timeline + sharing.",
  },
  {
    id: "leaderboards",
    href: "/app/leaderboards",
    label: "Leaderboards",
    audience: "authenticated",
    nav: true,
    flag: "leaderboards",
    implemented: true,
    description:
      "Opt-in leaderboards: lifts, rep PRs, technique improvement, consistency — labeled verification, no fake ranks.",
  },
  {
    id: "verified-lifts",
    href: "/app/verified-lifts",
    label: "Verified lifts",
    audience: "authenticated",
    nav: true,
    flag: "verifiedLifts",
    implemented: true,
    description:
      "Lift verification: self-reported, video submitted, competition verified — badges; never officially verified without criteria.",
  },
  {
    id: "challenges",
    href: "/app/challenges",
    label: "Challenges",
    audience: "authenticated",
    nav: true,
    flag: "challengeEngine",
    implemented: true,
    description:
      "Community challenges rewarding consistency, learning, and improvement — optional leaderboards; no max-daily-lift races.",
  },
  {
    id: "achievements",
    href: "/app/achievements",
    label: "Achievements",
    audience: "authenticated",
    nav: true,
    flag: "achievementSystem",
    implemented: true,
    description:
      "Meaningful milestones: first workout, technique, PRs, consistency — no empty gamification.",
  },
  {
    id: "athlete-level",
    href: "/app/athlete-level",
    label: "Athlete Level",
    audience: "authenticated",
    nav: true,
    flag: "athleteLevel",
    implemented: true,
    description:
      "Optional multi-factor level (Foundation→Elite). Not absolute strength; Elite needs competitive evidence.",
  },
  {
    id: "community-qa",
    href: "/app/community-qa",
    label: "Knowledge Q&A",
    audience: "authenticated",
    nav: true,
    flag: "communityQa",
    implemented: true,
    description:
      "Community Q&A: categories, voting, accepted answers, expert badges — AI summarizes only, never impersonates.",
  },
  {
    id: "expert-contributor",
    href: "/app/expert-contributor",
    label: "Expert Contributor",
    audience: "authenticated",
    nav: true,
    flag: "expertContributor",
    implemented: true,
    description:
      "Coach / Verified Coach / Expert Contributor roles — explicit verification; expert articles + SEO author schema.",
  },
  {
    id: "technique-review",
    href: "/app/technique-review",
    label: "Technique review",
    audience: "authenticated",
    nav: true,
    flag: "techniqueExpertReview",
    implemented: true,
    description:
      "Optional expert review of technique AI analyses — Confirm / Correct / Comment; never auto-retrain.",
  },
  {
    id: "human-analysis",
    href: "/app/human-analysis",
    label: "Expert review (paid)",
    audience: "authenticated",
    nav: true,
    flag: "humanAnalysisProduct",
    implemented: true,
    description:
      "Paid Expert Technique Review — single lift, training, competition prep; status tracking; no invented SLA.",
  },
  {
    id: "performance-report",
    href: "/app/performance-report",
    label: "Performance report",
    audience: "authenticated",
    nav: true,
    flag: "performanceReportPdf",
    implemented: true,
    description:
      "Premium downloadable athlete PDF — period, missing data, estimated metrics labeled.",
  },
  {
    id: "monthly-report",
    href: "/app/monthly-report",
    label: "Monthly report",
    audience: "authenticated",
    nav: true,
    flag: "monthlyPerformanceReport",
    implemented: true,
    description:
      "Automatic monthly performance report — archive + shareable public-safe summary.",
  },
  {
    id: "training-style",
    href: "/app/training-style",
    label: "Training style",
    audience: "authenticated",
    nav: true,
    flag: "trainingStyleProfiler",
    implemented: true,
    description:
      "Practical training preferences (intensity, frequency, volume) — not personality claims.",
  },
  {
    id: "personalization",
    href: "/app/personalization",
    label: "Personalization",
    audience: "authenticated",
    nav: true,
    flag: "personalizationEngine",
    implemented: true,
    description:
      "Central personalization engine for dashboard, recommendations, programs, alternatives, content, notifications — never pricing from sensitive traits.",
  },
  {
    id: "notifications",
    href: "/app/notifications",
    label: "Notifications",
    audience: "authenticated",
    nav: true,
    flag: "smartNotifications",
    implemented: true,
    description:
      "Smart notifications with push/email/in-app controls and frequency preferences — anti-spam.",
  },
  {
    id: "retention",
    href: "/app/retention",
    label: "Retention",
    audience: "authenticated",
    nav: true,
    flag: "behavioralRetention",
    implemented: true,
    description:
      "Ethical follow-through loops (workout streak, weekly review, goals, technique) — planned rest counts; no dark patterns.",
  },
  {
    id: "monthly-report-share",
    href: "/share/monthly/[token]",
    label: "Monthly report share",
    audience: "public",
    nav: false,
    flag: "monthlyPerformanceReport",
    implemented: true,
    description: "Public-safe monthly report highlight card.",
  },
  {
    id: "weekly-review",
    href: "/app/weekly-review",
    label: "Weekly review",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Automatic weekly performance review with this-vs-previous week and stored history.",
  },
  {
    id: "recovery",
    href: "/app/recovery",
    label: "Recovery",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Daily recovery check-in, Recovery Readiness estimate, trends — not medical accuracy.",
  },
  {
    id: "nutrition",
    href: "/app/nutrition",
    label: "Nutrition",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "Mealnexio nutrition status, deep-link CTA, daily targets when synced — never fake macros.",
  },
  {
    id: "nutrition-mealnexio-return",
    href: "/app/nutrition/mealnexio-return",
    label: "Mealnexio return",
    audience: "authenticated",
    nav: false,
    flag: "mealnexioDeepLinking",
    implemented: true,
    description:
      "Return landing for Mealnexio nutrition summary handoff — invents nothing while protocol is not live.",
  },
  {
    id: "insights",
    href: "/app/insights",
    label: "Insights",
    audience: "authenticated",
    nav: true,
    flag: "appInsights",
    implemented: true,
    description:
      "Cross-domain insights: training, recovery, nutrition, body metrics — evidence, confidence, action.",
  },
  {
    id: "coach-brain",
    href: "/app/coach-brain",
    label: "AI Coach",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description:
      "AI Coach chat + structured recommendations from athlete data; never auto-applies programs.",
  },
  {
    id: "app-methods",
    href: "/app/methods",
    label: "Methods",
    audience: "authenticated",
    nav: true,
    flag: "appMethods",
    implemented: true,
    description: "In-app training-method knowledge browser.",
  },
  {
    id: "app-method-detail",
    href: "/app/methods/[slug]",
    label: "Method detail",
    audience: "authenticated",
    nav: false,
    flag: "appMethods",
    implemented: true,
    description: "In-app training-method detail.",
  },
  {
    id: "coach",
    href: "/app/coach",
    label: "Coach",
    audience: "authenticated",
    nav: true,
    flag: "appCoach",
    implemented: true,
    description:
      "Multi-athlete coach dashboard — prioritized attention queue, roster, activity (grants only).",
  },
  {
    id: "org",
    href: "/app/org",
    label: "Organizations",
    audience: "authenticated",
    nav: true,
    flag: "gymTeamDashboard",
    implemented: true,
    description:
      "Gym / team organizations — members, teams, aggregate adherence & participation (opt-in; no private data bypass).",
  },
  {
    id: "org-detail",
    href: "/app/org/[orgId]",
    label: "Organization dashboard",
    audience: "authenticated",
    nav: false,
    flag: "gymTeamDashboard",
    implemented: true,
    description:
      "Organization analytics: adherence, participation, performance trends for opted-in athletes only.",
  },
  {
    id: "org-billing",
    href: "/app/org/[orgId]/billing",
    label: "Organization billing",
    audience: "authenticated",
    nav: false,
    flag: "orgBilling",
    implemented: true,
    description:
      "B2B org billing — coach/athlete seats, usage limits, features, upgrade (prices via env only).",
  },
  {
    id: "coach-marketplace",
    href: "/app/coach/marketplace",
    label: "Marketplace listing",
    audience: "authenticated",
    nav: false,
    flag: "coachMarketplace",
    implemented: true,
    description:
      "Coach marketplace listing controls — availability, pricing, specializations, consultation inbox.",
  },
  {
    id: "coach-athlete",
    href: "/app/coach/[athleteProfileId]",
    label: "Coach athlete",
    audience: "authenticated",
    nav: false,
    flag: "appCoach",
    implemented: true,
    description:
      "Permissioned coach athlete workspace (overview, training, technique, progress, recovery, notes, recommendations, AI Copilot).",
  },
  {
    id: "app-academy",
    href: "/app/academy",
    label: "Academy",
    audience: "authenticated",
    nav: true,
    flag: "appAcademy",
    implemented: true,
    description: "Student dashboard — enrollments, progress, certificates, learning paths (Academy 2.0).",
  },
  {
    id: "app-academy-course",
    href: "/app/academy/[slug]",
    label: "Academy course",
    audience: "authenticated",
    nav: false,
    flag: "appAcademy",
    implemented: true,
    description:
      "In-app course learning with lessons, quizzes, prerequisites, and practical assignments.",
  },
  {
    id: "settings",
    href: "/app/settings",
    label: "Settings",
    audience: "authenticated",
    nav: true,
    implemented: true,
    description: "Account, preferences, and profile settings.",
  },
  {
    id: "settings-consent",
    href: "/app/settings/consent",
    label: "Consent preferences",
    audience: "authenticated",
    nav: false,
    flag: "modelImprovementConsent",
    implemented: true,
    description:
      "Unbundled consent — service use, expert review, research/model improvement; revoke where applicable.",
  },
  {
    id: "admin",
    href: "/app/admin",
    label: "Admin",
    audience: "authenticated",
    nav: false,
    implemented: true,
    description:
      "Staff CMS — server-side isAdmin only; never shown in athlete nav.",
  },
  {
    id: "admin-ai-cost",
    href: "/app/admin/ai-cost",
    label: "AI cost",
    audience: "authenticated",
    nav: false,
    flag: "aiCostControl",
    implemented: true,
    description:
      "Internal AI cost control dashboard — routing policy, cache, cost per feature (admin only).",
  },
  {
    id: "admin-ai-router",
    href: "/app/admin/ai-router",
    label: "AI router",
    audience: "authenticated",
    nav: false,
    flag: "aiModelRouter",
    implemented: true,
    description:
      "Multi-model AI router — provider chains, fallbacks, latency/error/cost logs (admin only).",
  },
  {
    id: "admin-ai-observability",
    href: "/app/admin/ai-observability",
    label: "AI observability",
    audience: "authenticated",
    nav: false,
    flag: "aiObservability",
    implemented: true,
    description:
      "AI observability — requests, success, latency, cost, failures, feedback (admin only; no raw inputs).",
  },
  {
    id: "admin-i18n",
    href: "/app/admin/i18n",
    label: "Internationalization",
    audience: "authenticated",
    nav: false,
    flag: "i18n",
    implemented: true,
    description:
      "i18n architecture — English catalogs, planned CS/DE/ES/AR, terminology review (admin).",
  },
  {
    id: "admin-unit-system",
    href: "/app/admin/unit-system",
    label: "Unit system",
    audience: "authenticated",
    nav: false,
    flag: "unitSystem",
    implemented: true,
    description:
      "Global units — canonical kg/cm/m; kg/lb, cm/ft/in, km/mi presentation (admin).",
  },
  {
    id: "admin-timezone-system",
    href: "/app/admin/timezone-system",
    label: "Timezone system",
    audience: "authenticated",
    nav: false,
    flag: "timezoneSystem",
    implemented: true,
    description:
      "Timezone system — store UTC, display local for workouts/comps/notifications/messages (admin).",
  },
  {
    id: "admin-accessibility",
    href: "/app/admin/accessibility",
    label: "Accessibility 2.0",
    audience: "authenticated",
    nav: false,
    flag: "accessibilitySystem",
    implemented: true,
    description:
      "WCAG audit — keyboard, SR, charts, video, forms, modals, focus traps; scores not color-only (admin).",
  },
  {
    id: "admin-performance",
    href: "/app/admin/performance",
    label: "Performance 2.0",
    audience: "authenticated",
    nav: false,
    flag: "performanceSystem",
    implemented: true,
    description:
      "Core Web Vitals budgets — homepage, dashboard, exercises, technique (admin).",
  },
  {
    id: "admin-database-scale",
    href: "/app/admin/database-scale",
    label: "Database scale",
    audience: "authenticated",
    nav: false,
    flag: "databaseScale",
    implemented: true,
    description:
      "DB scale audit — indexes, N+1, pagination, large tables; no premature shard (admin).",
  },
  {
    id: "admin-event-driven",
    href: "/app/admin/event-driven",
    label: "Event-driven",
    audience: "authenticated",
    nav: false,
    flag: "eventDrivenArchitecture",
    implemented: true,
    description:
      "Domain events + in-process queue — technique, workout, PR, weekly review, billing (admin).",
  },
  {
    id: "admin-observability",
    href: "/app/admin/observability",
    label: "Observability",
    audience: "authenticated",
    nav: false,
    flag: "productionObservability",
    implemented: true,
    description:
      "Production monitoring — errors, latency, DB, jobs, payments, technique; correlation IDs (admin).",
  },
  {
    id: "admin-backup-recovery",
    href: "/app/admin/backup-recovery",
    label: "Backup & recovery",
    audience: "authenticated",
    nav: false,
    flag: "backupRecovery",
    implemented: true,
    description:
      "Disaster recovery runbook — DB/file backups, restore tests, video retention (admin).",
  },
  {
    id: "admin-billing-2",
    href: "/app/admin/billing-2",
    label: "Billing 2.0",
    audience: "authenticated",
    nav: false,
    flag: "billing2",
    implemented: true,
    description:
      "Billing 2.0 — trials, coupons, upgrades, grace, invoices, webhook idempotency (admin).",
  },
  {
    id: "admin-entitlements",
    href: "/app/admin/entitlements",
    label: "Entitlements",
    audience: "authenticated",
    nav: false,
    flag: "entitlementSystem",
    implemented: true,
    description:
      "Central EntitlementService — technique, AI Coach, analytics, coach tools, programs (admin).",
  },
  {
    id: "admin-growth-experiments",
    href: "/app/admin/growth-experiments",
    label: "Growth experiments",
    audience: "authenticated",
    nav: false,
    flag: "growthExperiments",
    implemented: true,
    description:
      "Safe A/B — homepage CTA, onboarding, pricing; never safety/privacy/medical (admin).",
  },
  {
    id: "admin-activation-metrics",
    href: "/app/admin/activation-metrics",
    label: "Activation metrics",
    audience: "authenticated",
    nav: false,
    flag: "activationMetrics",
    implemented: true,
    description:
      "Product activation — onboarding, first workout, first technique, D7 return (admin).",
  },
  {
    id: "admin-retention-analytics",
    href: "/app/admin/retention-analytics",
    label: "Retention analytics",
    audience: "authenticated",
    nav: false,
    flag: "retentionAnalytics",
    implemented: true,
    description:
      "D1/D7/D30, subscription & feature retention; action correlations ≠ causation (admin).",
  },
  {
    id: "admin-conversion-funnel",
    href: "/app/admin/conversion-funnel",
    label: "Conversion funnel",
    audience: "authenticated",
    nav: false,
    flag: "conversionFunnel",
    implemented: true,
    description:
      "Homepage → Paid funnel visualization and ranked drop-offs (admin).",
  },
  {
    id: "admin-user-segmentation",
    href: "/app/admin/user-segmentation",
    label: "User segmentation",
    audience: "authenticated",
    nav: false,
    flag: "userSegmentation",
    implemented: true,
    description:
      "Beginner/Advanced/sport/Coach/Paid/High engagement — no sensitive demographics (admin).",
  },
  {
    id: "admin-personalized-homepage",
    href: "/app/admin/personalized-homepage",
    label: "Personalized homepage",
    audience: "authenticated",
    nav: false,
    flag: "personalizedHomepage",
    implemented: true,
    description:
      "Traffic-intent homepage variants — brand + SEO locked; no cloaking (admin).",
  },
  {
    id: "admin-programmatic-seo-safety",
    href: "/app/admin/programmatic-seo-safety",
    label: "Programmatic SEO",
    audience: "authenticated",
    nav: false,
    flag: "programmaticSeoSafety",
    implemented: true,
    description:
      "Quality-gated programmatic guides — refuse thin page factories (admin).",
  },
  {
    id: "admin-exercise-comparison",
    href: "/app/admin/exercise-comparison",
    label: "Exercise comparison",
    audience: "authenticated",
    nav: false,
    flag: "exerciseComparison",
    implemented: true,
    description:
      "Exercise A vs B engine — dimensions + SEO allowlisted pairs (admin).",
  },
  {
    id: "admin-sport-goal-landings",
    href: "/app/admin/sport-goal-landings",
    label: "Sport goal landings",
    audience: "authenticated",
    nav: false,
    flag: "sportGoalLandings",
    implemented: true,
    description:
      "High-quality /goals landings with product CTAs — no SEO filler (admin).",
  },
  {
    id: "admin-calculator-suite",
    href: "/app/admin/calculator-suite",
    label: "Calculator suite",
    audience: "authenticated",
    nav: false,
    flag: "calculatorSuite",
    implemented: true,
    description:
      "Training calculators — precision honesty + product CTAs (admin).",
  },
  {
    id: "admin-technique-check",
    href: "/app/admin/technique-check",
    label: "Technique check funnel",
    audience: "authenticated",
    nav: false,
    flag: "techniqueCheck",
    implemented: true,
    description:
      "Free technique check acquisition funnel — privacy + rate limits (admin).",
  },
  {
    id: "admin-program-audit",
    href: "/app/admin/program-audit",
    label: "Program audit funnel",
    audience: "authenticated",
    nav: false,
    flag: "programAudit",
    implemented: true,
    description:
      "Free program audit — deterministic checks, no fake scoring (admin).",
  },
  {
    id: "admin-athlete-assessment",
    href: "/app/admin/athlete-assessment",
    label: "Athlete assessment funnel",
    audience: "authenticated",
    nav: false,
    flag: "athleteAssessment",
    implemented: true,
    description:
      "Free athlete assessment — Self-assessment estimate; Not full Athlete Score (admin).",
  },
  {
    id: "admin-on-site-education",
    href: "/app/admin/on-site-education",
    label: "On-site education",
    audience: "authenticated",
    nav: false,
    flag: "onSiteEducation",
    implemented: true,
    description:
      "Learn why catalog — in-context metric education (admin).",
  },
  {
    id: "admin-micro-learning",
    href: "/app/admin/micro-learning",
    label: "Micro-learning",
    audience: "authenticated",
    nav: false,
    flag: "microLearning",
    implemented: true,
    description:
      "Personalized 1-minute cards with anti-spam caps (admin).",
  },
  {
    id: "admin-academy-20",
    href: "/app/admin/academy",
    label: "Academy 2.0",
    audience: "authenticated",
    nav: false,
    flag: "academy20",
    implemented: true,
    description:
      "Academy 2.0 — paths, prerequisites, assignments, knowledge progress (admin).",
  },
  {
    id: "admin-certificate-verification",
    href: "/app/admin/certificate-verification",
    label: "Certificate verification",
    audience: "authenticated",
    nav: false,
    flag: "certificateVerification",
    implemented: true,
    description:
      "Public Certificate of Completion verify — honesty + fields (admin).",
  },
  {
    id: "admin-enterprise-security",
    href: "/app/admin/enterprise-security",
    label: "Enterprise security",
    audience: "authenticated",
    nav: false,
    flag: "enterpriseSecurity",
    implemented: true,
    description:
      "B2B security prep — access, encryption, processing, logging, backups, IR; no fake compliance certs.",
  },
  {
    id: "admin-gdpr-readiness",
    href: "/app/admin/gdpr-readiness",
    label: "GDPR readiness",
    audience: "authenticated",
    nav: false,
    flag: "gdprReadiness",
    implemented: true,
    description:
      "GDPR-supporting workflows — consent, export, deletion, cookies, retention; legal review markers.",
  },
  {
    id: "admin-video-privacy",
    href: "/app/admin/video-privacy",
    label: "Video privacy",
    audience: "authenticated",
    nav: false,
    flag: "videoPrivacyControls",
    implemented: true,
    description:
      "Per-video privacy — private by default; analysis / expert / model-improvement opt-ins.",
  },
  {
    id: "admin-model-improvement-consent",
    href: "/app/admin/model-improvement-consent",
    label: "Model improvement consent",
    audience: "authenticated",
    nav: false,
    flag: "modelImprovementConsent",
    implemented: true,
    description:
      "Unbundled consent kinds — service use, expert review, research; revoke paths.",
  },
  {
    id: "admin-safety-system",
    href: "/app/admin/safety-system",
    label: "Safety System 2.0",
    audience: "authenticated",
    nav: false,
    flag: "safetySystem20",
    implemented: true,
    description:
      "Central recommendation safety — frequency, volume, weight loss, diagnosis, pain-ignoring.",
  },
  {
    id: "admin-red-team-ai-coach",
    href: "/app/admin/red-team-ai-coach",
    label: "Red Team AI Coach",
    audience: "authenticated",
    nav: false,
    flag: "redTeamAiCoach",
    implemented: true,
    description:
      "Adversarial Coach chat QA — refuse unsafe maxes, diagnosis, guaranteed gains; document failures.",
  },
  {
    id: "admin-product-trust-audit",
    href: "/app/admin/product-trust-audit",
    label: "Product Trust Audit",
    audience: "authenticated",
    nav: false,
    flag: "productTrustAudit",
    implemented: true,
    description:
      "AI feature trust registry — provenance, confidence, certainty risk, challenge paths.",
  },
  {
    id: "admin-mobile-workout",
    href: "/app/admin/mobile-workout",
    label: "Mobile workout",
    audience: "authenticated",
    nav: false,
    flag: "mobileWorkoutExperience",
    implemented: true,
    description:
      "Mobile-first live workout — one-hand focus, steppers, auto-save, rest timer, previous performance.",
  },
  {
    id: "admin-pwa-readiness",
    href: "/app/admin/pwa-readiness",
    label: "PWA readiness",
    audience: "authenticated",
    nav: false,
    flag: "pwaReadiness",
    implemented: true,
    description:
      "Installable PWA — offline shell, cached workout, sync; never cache sensitive content insecurely.",
  },
  {
    id: "admin-wearable-integration",
    href: "/app/admin/wearable-integration",
    label: "Wearable integration",
    audience: "authenticated",
    nav: false,
    flag: "wearableIntegration",
    implemented: true,
    description:
      "Wearable adapter registry — Apple Health, Health Connect, Garmin, Whoop, Oura; no fake connections.",
  },
  {
    id: "admin-device-data-normalization",
    href: "/app/admin/device-data-normalization",
    label: "Device data normalization",
    audience: "authenticated",
    nav: false,
    flag: "deviceDataNormalization",
    implemented: true,
    description:
      "Canonical sleep / HR / HRV / steps / workouts — source metadata; no cross-device identity without caveats.",
  },
  {
    id: "admin-mealnexio-deep-linking",
    href: "/app/admin/mealnexio-deep-linking",
    label: "Mealnexio deep linking",
    audience: "authenticated",
    nav: false,
    flag: "mealnexioDeepLinking",
    implemented: true,
    description:
      "Cross-product Mealnexio CTAs + return landing + SSO stub — never fakes sync or sessions.",
  },
  {
    id: "admin-command-center",
    href: "/app/admin/command-center",
    label: "Command Center",
    audience: "authenticated",
    nav: false,
    flag: "commandCenter",
    implemented: true,
    description:
      "Performance OS Command Center — section catalog, fold policy, adaptive layout, widget prefs.",
  },
  {
    id: "admin-custom-dashboards",
    href: "/app/admin/custom-dashboards",
    label: "Custom dashboards",
    audience: "authenticated",
    nav: false,
    flag: "customDashboards",
    implemented: true,
    description:
      "Dashboard focus presets (Strength→Bodybuilding), smart defaults, save layout.",
  },
  {
    id: "admin-command-palette",
    href: "/app/admin/command-palette",
    label: "Command palette",
    audience: "authenticated",
    nav: false,
    flag: "commandPalette",
    implemented: true,
    description:
      "Power-user command palette — Ctrl/Cmd+Shift+P; keyboard accessible navigation.",
  },
  {
    id: "admin-universal-timeline",
    href: "/app/admin/universal-timeline",
    label: "Universal timeline",
    audience: "authenticated",
    nav: false,
    flag: "universalTimeline",
    implemented: true,
    description:
      "Athlete history timeline event kinds — workout through coach note; filters.",
  },
  {
    id: "admin-performance-story",
    href: "/app/admin/performance-story",
    label: "Performance Story",
    audience: "authenticated",
    nav: false,
    flag: "performanceStory",
    implemented: true,
    description:
      "Yearly performance narrative + shareable review — no fake causal conclusions.",
  },
  {
    id: "admin-year-in-review",
    href: "/app/admin/year-in-review",
    label: "Year in Review",
    audience: "authenticated",
    nav: false,
    flag: "yearInReview",
    implemented: true,
    description:
      "Annual athlete report cards — sessions, PRs, technique, consistency, competition.",
  },
  {
    id: "admin-social-graph",
    href: "/app/admin/social-graph",
    label: "Social graph prep",
    audience: "authenticated",
    nav: false,
    flag: "socialGraphPrep",
    implemented: true,
    description:
      "Follow athletes/coaches, private accounts, activity feed contracts — no live feed without moderation gate.",
  },
  {
    id: "admin-activity-feed",
    href: "/app/admin/activity-feed",
    label: "Activity Feed MVP",
    audience: "authenticated",
    nav: false,
    flag: "activityFeedMvp",
    implemented: true,
    description:
      "Optional milestone feed kinds + anti-dark-pattern rules; distinct from gated social follower feed.",
  },
  {
    id: "admin-live-competition",
    href: "/app/admin/live-competition",
    label: "Live Competition Mode",
    audience: "authenticated",
    nav: false,
    flag: "liveCompetitionMode",
    implemented: true,
    description:
      "Meet-day architecture — attempts, results, next attempt, warm-up timing, offline; no unsafe instructions.",
  },
  {
    id: "admin-warmup-generator",
    href: "/app/admin/warmup-generator",
    label: "Warm-up generator",
    audience: "authenticated",
    nav: false,
    flag: "warmupGenerator",
    implemented: true,
    description:
      "Progressive warm-up ladders — conservative defaults, fatigue caps, user-editable sets.",
  },
  {
    id: "admin-session-readiness",
    href: "/app/admin/session-readiness",
    label: "Session readiness",
    audience: "authenticated",
    nav: false,
    flag: "sessionReadinessAdjuster",
    implemented: true,
    description:
      "Pre-workout proceed / minor adjustment / review load — never cancel from one metric.",
  },
  {
    id: "admin-live-session-autoregulation",
    href: "/app/admin/live-session-autoregulation",
    label: "Live session autoregulation",
    audience: "authenticated",
    nav: false,
    flag: "liveSessionAutoregulation",
    implemented: true,
    description:
      "During-workout RPE vs planned — suggest reduce next set; confirm required; never auto-apply.",
  },
] as const;

function isRouteEnabled(route: AppRoute): boolean {
  if (!route.flag) return true;
  return featureFlags[route.flag];
}

export function getPublicNavRoutes(): AppRoute[] {
  return routes.filter(
    (route) =>
      route.audience === "public" &&
      route.nav &&
      route.implemented &&
      isRouteEnabled(route),
  );
}

export function getAuthenticatedNavRoutes(): AppRoute[] {
  return routes.filter(
    (route) =>
      route.audience === "authenticated" &&
      route.nav &&
      route.implemented &&
      isRouteEnabled(route),
  );
}

export function isFeatureEnabled(flag: FeatureFlagKey | undefined): boolean {
  if (!flag) return true;
  return featureFlags[flag];
}
