import { L } from "@/domain/legendary-methods/localized";
import type { LegendaryMethodSectionId } from "@/domain/legendary-methods/types";
import type { LocalizedString } from "@/domain/legendary-methods/localized";

/** Fully bilingual narrative bodies for the Arnold Golden Era profile. */
export const ARNOLD_SECTION_BODIES: Partial<
  Record<LegendaryMethodSectionId, LocalizedString>
> = {
  "athlete-and-era": L(
    `Arnold Schwarzenegger’s competitive bodybuilding rise sits inside what later writers call the Golden Era: a culture of high training density, physique aesthetics as the scoring criterion, and gyms that normalised long sessions. The relevant stage for this analysis is not celebrity biography — it is the period when his training ideas were formalised for a mass audience through major books, especially The New Encyclopedia of Modern Bodybuilding (with Bill Dobbins) and earlier autobiographical training narrative in Arnold: The Education of a Bodybuilder.

In that context, “volume” is not a single number. It is a package: how often a muscle is trained each week, how many exercises and sets appear in a session, how little rest is left between paired movements, and how close sets are taken to failure. Golden Era culture rewarded visible muscularity under stage lighting. That incentive structure pulled programmes toward frequent stimulation and high local fatigue, not toward the sparse templates popular in some modern strength sports.

It also mattered who was recovering. Competitive bodybuilders of that era often organised life around training, food, and sleep in ways recreational lifters cannot. Any honest analysis has to separate the published training ideas from the support systems around them.

Double-split claims belong in this era discussion as a contextual tactic, not as a timeless commandment. Training twice in one day appears in popular and published discussions of high-ambition phases when schedule and recovery support allowed denser weekly stimulus. That is different from asserting that every year of Arnold’s career ran the same double-day calendar. Ordinary lifters reading secondary charts often miss that distinction and treat a competition-phase density tool as a permanent identity.`,
    `Vzestup Arnolda Schwarzeneggera v soutěžní kulturistice spadá do období, které pozdější autoři nazývají Zlatá éra: kultura vysoké tréninkové hustoty, kde estetika fyzika byla hodnoticím kritériem a posilovny normalizovaly dlouhé jednotky. Relevantní rovina této analýzy není celebritní biografie — je to období, kdy se jeho tréninkové myšlenky formalizovaly pro masové publikum v klíčových knihách, zejména The New Encyclopedia of Modern Bodybuilding (s Billem Dobbinsem) a dřívějším autobiografickém vyprávění Arnold: The Education of a Bodybuilder.

V tomto kontextu není „Objem“ jedno číslo. Je to balík: jak často je sval trénován týdně, kolik cviků a sérií je v jednotce, jak málo odpočinku zůstává mezi párovanými pohyby a jak blízko k selhání se série dotahují. Kultura Zlaté éry odměňovala viditelnou muskulaturu pod jevištním světlem. Tato motivační struktura tlačila programy k časté stimulaci a vysoké lokální únavě — ne k řídkým šablonám populárním v některých moderních silových sportech.

Záleželo i na tom, kdo regeneruje. Soutěžní kulturisté té éry často organizovali život kolem tréninku, jídla a spánku způsobem, který rekreační lifter nemá. Poctivá analýza musí oddělit publikované tréninkové ideje od podpůrných systémů kolem nich.

Tvrzení o double-splitu patří do diskuse o této éře jako kontextová taktika, ne jako věčné přikázání. Trénink dvakrát denně se objevuje v populárních i publikovaných popisech fází vysokých ambicí, kdy rozvrh a Regenerace dovolily hustší týdenní stimulus. To není totéž jako tvrdit, že každý rok Arnoldovy kariéry běžel stejný double-day kalendář. Běžní lifteři u sekundárních tabulek ten rozdíl často minou a nástroj soutěžní hustoty berou jako permanentní identitu.`,
  ),
  "documented-training-method": L(
    `Documented discussions of Arnold’s approach repeatedly emphasise high set volume for body parts, training major groups multiple times per week in competition-oriented templates, and heavy use of intensity techniques — especially supersets.

In later instructional writing attributed to Arnold (including FLEX/Muscle & Fitness columns and material hosted on schwarzenegger.com), supersets are defined as performing two exercises successively with little or no rest. A preferred pairing pattern is antagonist work: chest with back, biceps with triceps, quadriceps with hamstrings. The stated rationale is practical densification (more work per unit time) and a claimed neuromuscular priming effect when a pull is followed by a push (or vice versa). Same-muscle compound sets (two exercises for one body part back-to-back) are also described as a way to raise metabolic stress and time under tension.

Exercise selection in the published teaching tradition favours a blend of free-weight compounds and classical isolation finishers rather than novelty for its own sake. Progression is culturally framed as continual improvement — more load, more quality reps, or denser work — rather than as a modern percentage-based peaking wave. Differences between documented routines from different periods are expected: career phase, contest proximity, and publication edition all change the chart a reader finds.

Important uncertainty: popular internet “Arnold routines” often present one split as permanent. Published sources and secondary summaries describe more than one competition-era structure (including variations where major groups appear roughly twice weekly versus higher-frequency examples). Because those templates differ, this profile treats high frequency and high volume as the durable theme — not one immortal weekly timetable.

What is not claimed here: a verbatim reproduction of encyclopedia tables, set-by-set prescriptions, or any assertion that a blog PDF is “Arnold’s exact permanent programme.” Where secondary sites reprint detailed charts, they are treated as contested popularisations unless tied back to the books themselves.`,
    `Dokumentované diskuse o Arnoldově přístupu opakovaně zdůrazňují vysoký Objem sérií na partie, trénink hlavních skupin vícekrát týdně v soutěžních šablonách a těžké využívání intenzifikačních technik — především supersetů.

V pozdějších instruktážních textech přisuzovaných Arnoldovi (včetně sloupků FLEX/Muscle & Fitness a materiálů na schwarzenegger.com) jsou supersety definovány jako dva cviky po sobě s minimálním nebo nulovým odpočinkem. Preferované párování je antagonistické: hrudník se zády, biceps s tricepsem, kvadriceps s hamstringy. Uváděný důvod je praktické zhuštění (více práce za čas) a tvrzený neuromuskulární priming, když tah následuje tlak (nebo naopak). Same-muscle compound sety (dva cviky na jednu partii back-to-back) se popisují jako cesta ke zvýšení metabolického stresu a času pod napětím.

Výběr cviků v publikované tradici míchá volné compoundy a klasické izolační finishery — ne novotu pro novotu. Progrese je kulturně rámovaná jako permanentní zlepšení — více zátěže, více kvalitních opakování nebo hustší práce — ne jako moderní procentuální peaking vlna. Rozdíly mezi dokumentovanými rutinami z různých období jsou očekávané: fáze kariéry, blízkost závodu i vydání publikace mění tabulku, kterou čtenář najde.

Důležitá nejistota: populární internetové „Arnold routines“ často prezentují jeden split jako permanentní. Publikované zdroje a sekundární shrnutí popisují víc než jednu soutěžní strukturu (včetně variant, kde hlavní skupiny jdou zhruba 2× týdně, versus vyšší Frekvence). Protože se šablony liší, tento profil bere vysokou Frekvenci a vysoký Objem jako trvanlivé téma — ne jeden nesmrtelný týdenní jízdní řád.

Co zde netvrdíme: doslovnou reprodukci encyklopedických tabulek, předpis série po sérii, ani že blogové PDF je „Arnoldův přesný permanentní program“. Kde sekundární weby tisknou detailní charty, bereme je jako sporné popularizace, dokud nejsou ukotvené v knihách.`,
  ),
  "training-structure": L(
    `Structurally, Golden Era volume training (as associated with Arnold’s published teaching) tends to organise the week around body-part coverage rather than a single full-body strength practice. Sessions often stack multiple exercises per muscle, then rotate through the body across consecutive training days.

Frequency is a first-class variable. Documented competition-oriented examples associated with the encyclopedia tradition describe major muscle groups appearing more than once per week. That raises both stimulus and recovery cost compared with once-weekly “bro split” stereotypes.

Volume distribution typically favours the showpiece upper-body musculature and legs with large absolute set counts, while calves, arms, and midsection receive dedicated high-repetition work in many popular accounts. Intensity distribution mixes heavier compound presses/rows/squats with higher-rep isolation finishers. Progression is framed culturally as continual improvement in load or work completed — not as a fixed percentage wave like modern powerlifting peaking models.

Recovery structure, in the books’ own framing, is not optional fluff: sleep, nutrition, and rest are presented as part of making extreme workloads productive. That is a critical teaching point for modern readers who copy the set counts and skip the recovery infrastructure.`,
    `Strukturálně má objemový trénink Zlaté éry (spojený s Arnoldovou publikovanou výukou) tendenci organizovat týden kolem pokrytí partií, ne kolem jednoho full-body silového tréninku. Jednotky často skládají více cviků na sval a pak rotují tělem napříč po sobě jdoucími dny.

Frekvence je proměnná první třídy. Dokumentované soutěžní příklady z encyklopedické tradice popisují hlavní svalové skupiny více než jednou týdně. To zvedá stimulus i cenu Regenerace oproti stereotypnímu „bro splitu“ jednou týdně.

Distribuce Objemu typicky favorizuje vlajkovou horní polovinu a nohy vysokými absolutními počty sérií; lýtka, paže a střed dostávají v populárních účtech dedikovanou high-rep práci. Distribuce Intenzity míchá těžší compound tlaky/tahy/dřepy s vyššími opakováními na izolacích. Progrese je kulturně rámovaná jako permanentní zlepšení zátěže nebo odvedené práce — ne jako fixní procentuální vlna moderního peakingu silového trojboje.

Struktura Regenerace v rámování samotných knih není volitelná omáčka: spánek, výživa a odpočinek jsou součástí toho, co dělá extrémní zátěž produktivní. To je kritická lekce pro moderní čtenáře, kteří kopírují počty sérií a vynechávají regenerační infrastrukturu.`,
  ),
  "volume-intensity-frequency": L(
    `From an independent coaching lens, the method’s signature is the product of three dials turned high at once: frequency × sets × effort.

Frequency multiplies practice opportunities and residual fatigue. High set volume multiplies local damage and metabolic stress. High effort (including failure-oriented culture in many accounts) multiplies the recovery bill further. Any one dial can be productive; all three together is an advanced strategy.

Ordinary lifters often misunderstand volume as “more exercises = more growth” without tracking weekly hard sets or performance. Golden Era templates can look like random exercise lists when stripped of progression rules. A better reading is: choose a manageable weekly set budget per muscle, distribute it across 2+ exposures if recovery allows, and use antagonist supersets to raise density without automatically adding rest-period fluff.

Conflicting information note: secondary websites disagree on exact weekly splits and set totals. Until a claim is pinned to a specific published edition and page context, treat numeric “Arnold did X sets of Y every Monday forever” statements as low confidence.`,
    `Z nezávislého koučovacího pohledu je podpis metody součinem tří dialů otočených nahoru najednou: Frekvence × série × úsilí.

Frekvence násobí příležitosti k praxi i reziduální únavu. Vysoký Objem sérií násobí lokální poškození a metabolický stres. Vysoké úsilí (včetně failure kultury v mnoha účtech) dál násobí účet za Regeneraci. Jeden dial může být produktivní; všechny tři najednou jsou pokročilá strategie.

Běžní lifteři často čtou Objem jako „více cviků = více růstu“ bez trackování týdenních hard setů nebo výkonu. Šablony Zlaté éry vypadají jako náhodné seznamy cviků, když z nich sundáte pravidla progrese. Lepší čtení: zvol zvládnutelný týdenní rozpočet sérií na sval, rozlož ho do 2+ expozic pokud Regenerace dovolí, a použij antagonistické supersety ke zvýšení hustoty bez automatického přidávání zbytečného odpočinku.

Poznámka ke konfliktním informacím: sekundární weby se rozcházejí v přesných týdenních splitech i součtech sérií. Dokud není tvrzení ukotvené v konkrétním vydání a kontextu stránky, ber číselná „Arnold dělal X sérií Y každé pondělí navždy“ jako nízkou důvěru.`,
  ),
  "why-it-worked": L(
    `Why such workloads could produce outstanding physiques for a tiny population of athletes is multi-factorial. Specificity favoured posing-relevant hypertrophy and muscular detail. Volume and frequency provided repeated high-tension practice. Technical practice on the same families of presses, rows, squats, and isolation movements was enormous across years. Athlete experience and selection effects matter: people who thrived under the culture stayed visible. Bodyweight and stage goals differed from powerlifting totals. Recovery resources (time, food, pharmacology contexts discussed historically in the sport, coaching environments) were often far above recreational norms. Sport demands rewarded looking a certain way on a certain day — not preserving joints for a decade of maximal singles.

Long-term adaptation for Arnold personally is inseparable from decades of progressive exposure. Copying the end-stage workload without the ramp is the classic error.

A useful way to read the success story without myth-making is to treat Golden Era volume as a high-dose hypertrophy laboratory that happened to be culturally fashionable. Antagonist supersets raised work density. High frequency kept skills sharp. Isolation finishers chased shape after compounds had already done the heavy structural work. None of those tools is magic in isolation; the combination, sustained for years by athletes who could recover, is what magazines later romanticised.

For coaches, the transferable lesson is not “do more forever.” It is that density tools, multi-exposure scheduling, and deliberate exercise variety can expand the hypertrophy toolbox — provided weekly hard-set budgets remain honest and recovery constraints are treated as hard limits rather than optional lifestyle advice.`,
    `Proč takové zátěže mohly u malé populace atletů vyprodukovat výjimečná fyzika, je multifaktoriální. Specifičnost favorizovala Hypertrofii relevantní pro pózování a svalový detail. Objem a Frekvence dodaly opakovanou praxi s vysokým napětím. Technická praxe na stejných rodinách tlaků, tahů, dřepů a izolací byla napříč lety enormní. Záleží na zkušenosti a selekci: kdo v kultuře prospíval, zůstal viditelný. Hmotnost a stage cíle se lišily od totálu silového trojboje. Regenerační zdroje (čas, jídlo, historicky diskutované farmakologické kontexty, koučovací prostředí) byly často daleko nad rekreační normou. Sport odměňoval vypadat určitým způsobem v určitý den — ne šetřit klouby deset let maximálních singlů.

Dlouhodobá adaptace u Arnolda osobně je neoddělitelná od desetiletí progresivní expozice. Kopírovat end-stage zátěž bez náběhu je klasická chyba.

Užitečné čtení úspěchu bez mýtů: Objem Zlaté éry jako vysokodávková hypertrofická laboratoř, která byla kulturně módní. Antagonistické supersety zvedly hustotu práce. Vysoká Frekvence držela skill ostrý. Izolační finishery honily tvar poté, co compoundy odvedly těžkou strukturální práci. Žádný nástroj sám není magie; kombinace, držená roky atlety, kteří dokázali regenerovat, je to, co časopisy později zromantizovaly.

Pro kouče: přenositelná lekce není „dělej víc navždy“. Je to, že nástroje hustoty, multi-exposure plánování a záměrná variace cviků rozšiřují hypertrofický toolbox — pokud týdenní hard-set rozpočty zůstanou poctivé a limity Regenerace jsou tvrdé hranice, ne volitelná lifestyle rada.`,
  ),
  "what-lifters-get-wrong": L(
    `Most lifters get Golden Era volume wrong by treating the highest reported templates as a personality test. They add supersets on day one, train close to failure on every set, sleep poorly, and call the method ineffective when they stall.

Other common mistakes: assuming one viral chart is the only authentic programme; ignoring that documented structures changed across career phases; using isolation volume before compounds are stable; and confusing “Arnold trained a lot” with “any high-rep pump work equals the method.”

Lifters also misread double-split claims. Training twice in a day can be a competition-phase density tactic for athletes with time, food, and recovery support — not a moral obligation for office workers. Another failure mode is copying exercise lists while ignoring progression: without tracking load, reps, or weekly hard sets, high volume becomes random fatigue.

This profile deliberately avoids medical diagnosis language. The practical warning is recovery economics: if performance, mood, and joint comfort are degrading week to week, volume is too high for your current constraints — regardless of whose name is on the PDF. Ordinary lifters should not copy the highest reported competition-era set counts exactly. Scale the principle; quarantine the celebrity dose.`,
    `Většina lifterů kazí Objem Zlaté éry tím, že nejvyšší reportované šablony berou jako osobnostní test. Přidají supersety den jedna, trénují blízko selhání každou sérii, spí špatně a metodu prohlásí za neúčinnou, když stagnují.

Další chyby: předpoklad, že jedna virální tabulka je jediný autentický program; ignorování, že dokumentované struktury se měnily napříč fázemi kariéry; izolace dřív, než jsou compoundy stabilní; záměna „Arnold trénoval hodně“ za „jakýkoli high-rep pump = metoda“.

Lifteři si také špatně čtou double-split. Trénink dvakrát denně může být taktika hustoty v soutěžní fázi pro atlety s časem, jídlem a Regenerací — ne morální povinnost pro office workery. Další failure mode: kopírovat seznamy cviků a ignorovat progresi — bez trackování zátěže, opakování nebo týdenních hard setů je vysoký Objem jen náhodná únava.

Tento profil záměrně nepoužívá medicínskou diagnostiku. Praktické varování je ekonomika Regenerace: pokud výkon, nálada a klouby padají týden po týdnu, je Objem příliš vysoký pro tvoje omezení — bez ohledu na jméno na PDF. Běžní lifteři nemají přesně kopírovat nejvyšší reportované soutěžní počty sérií. Škáluj princip; celebritní dávku dej do karantény.`,
  ),
  "risks-and-recovery": L(
    `Risk concentrates in tendons, lumbar tolerance under fatigue, and systemic under-recovery. High-frequency pressing and curling volumes can irritate elbows and shoulders when technique decays. Squatting and hinging under accumulated fatigue raise technical risk if ego loading replaces controlled reps.

Recovery demands scale with set counts and proximity to failure. Lifters without the ability to eat and sleep like a competitive bodybuilder should cut weekly hard sets first, not “try harder.” Deloads, exercise rotation, and capping failure sets are modern controls that preserve the useful ideas without importing the full historical dose.

A practical recovery checklist for anyone inspired by Golden Era density: protect seven-plus hours of sleep when possible, keep protein and total calories sufficient for the workload, schedule at least one easier week every four to six hard weeks, and stop adding exercises when the existing ones are already stalling. If antagonist supersets are used, rest between pairs still matters — density is a tool, not a race to collapse form.`,
    `Riziko se koncentruje ve šlachách, v toleranci beder pod únavou a v systémové podregeneraci. Vysokofrekvenční tlaky a curls můžou dráždit lokty a ramena, když technika padá. Dřepy a hinge pod kumulovanou únavou zvedají technické riziko, pokud ego loading nahradí kontrolovaná opakování.

Nároky na Regeneraci rostou s počtem sérií a blízkostí k selhání. Lifteři bez možnosti jíst a spát jako soutěžní kulturista mají nejdřív řezat týdenní hard sety — ne „snažit se víc“. Deloady, rotace cviků a strop na failure série jsou moderní kontroly, které zachovají užitečné ideje bez importu celé historické dávky.

Praktický checklist Regenerace pro inspiraci hustotou Zlaté éry: chraň 7+ hodin spánku když to jde, drž protein a celkové kalorie dost pro zátěž, naplánuj alespoň jeden lehčí týden každých 4–6 tvrdých týdnů a nepřidávej cviky, když ty stávající už stagnují. Pokud používáš antagonistické supersety, odpočinek mezi páry pořád počítá — hustota je nástroj, ne závod o kolaps formy.`,
  ),
  verdict: L(
    `The Strongest verdict: Golden Era volume training is historically important and still instructive for hypertrophy density and antagonist pairing — but it is a poor default for beginners and a dangerous cosplay target when copied at encyclopedia competition doses. Borrow principles; do not worship a single chart. Never treat any reconstructed week as Arnold’s permanent exact programme. The durable takeaways are multi-exposure frequency when recovered, antagonist densification used deliberately, and progression tracked honestly — not maximal set lists from contested secondary reprints.`,
    `Verdikt The Strongest: objemový trénink Zlaté éry je historicky důležitý a stále učí Hypertrofii, hustotu a antagonistické párování — ale je špatný default pro začátečníky a nebezpečný cosplay target, když se kopíruje v encyklopedických soutěžních dávkách. Půjč si principy; neuctívej jednu tabulku. Nikdy neber zrekonstruovaný týden jako Arnoldův permanentní přesný program. Trvanlivé takeaways: multi-exposure Frekvence když jsi zregenerovaný, záměrné antagonistické zhuštění a poctivě trackovaná progrese — ne maximalistické seznamy sérií ze sporných sekundárních reprintů.`,
  ),
  "modernised-application": L(
    `A modernised application keeps antagonist supersets, multi-exposure frequency where recovered, and progressive overload — while capping weekly hard sets, limiting failure, and protecting sleep. Beginners should not start here. Intermediates may run moderate volumes with one antagonist pairing block. Advanced physique athletes may push density in short mesocycles with planned deloads. See the structured modernAdaptation fields for dose guidance.

Practically, start by auditing current weekly hard sets per muscle, then decide whether frequency or density is the constraint you want to improve. Add one antagonist pairing (for example chest/back or biceps/triceps) for four weeks before expanding further. Keep most sets one to three reps in reserve. Treat any double-session day as an advanced, temporary experiment with reduced per-session volume — not as a lifestyle default. Related generic programmes on this site are the safer entry points when the goal is progressive overload without elite cosplay.`,
    `Modernizovaná aplikace drží antagonistické supersety, multi-exposure Frekvenci tam, kde Regenerace stačí, a Progresivní přetížení — zatímco stropuje týdenní hard sety, limituje failure a chrání spánek. Začátečníci sem nepatří. Intermediate můžou jet umírněný Objem s jedním blokem antagonistického párování. Pokročilí physique atleti můžou tlačit hustotu v krátkých mezocyklech s plánovanými deloady. Dávkování viz strukturovaná pole modernAdaptation.

Prakticky: audituj aktuální týdenní hard sety na sval, pak rozhodni, jestli chceš zlepšit Frekvenci nebo hustotu. Přidej jedno antagonistické párování (např. hrudník/záda nebo biceps/triceps) na čtyři týdny, než rozšíříš dál. Většinu sérií drž 1–3 opakování v rezervě. Double-session den ber jako pokročilý, dočasný experiment se sníženým Objemem na jednotku — ne jako lifestyle default. Související generické programy na tomto webu jsou bezpečnější vstup, když chceš Progresivní přetížení bez elitního cosplaye.`,
  ),
  "example-training-week": L(
    `See the labelled example week object. It is an original modernised illustration of frequency and antagonist density ideas — not a reprint of encyclopedia tables and not an athlete’s exact routine. Use it as a coaching sketch for intermediate densification, then adjust set counts to performance and recovery rather than to celebrity folklore.`,
    `Viz označený objekt ukázkového týdne. Je to originální modernizovaná ilustrace Frekvence a antagonistické hustoty — ne reprint encyklopedických tabulek a ne přesná rutina atleta. Použij ji jako koučovský náčrt pro intermediate zhuštění, pak uprav počty sérií podle výkonu a Regenerace — ne podle celebritního folklóru.`,
  ),
  sources: L(
    `Primary references are listed in the numbered Sources section: athlete-authored/co-authored books and instructional pieces on reputable channels. Secondary workout aggregators are not treated as primary evidence for exact permanent programmes. Where popular charts conflict with published teaching, this profile prefers the books and official instructional columns and marks numeric permanence claims as uncertain.`,
    `Primární odkazy jsou v číslované sekci Zdroje: knihy atleta / spoluautorů a instruktážní texty na seriózních kanálech. Sekundární agregátory tréninků nejsou primární evidence pro přesné permanentní programy. Kde populární charty kolidují s publikovanou výukou, tento profil preferuje knihy a oficiální sloupky a číselná tvrzení o permanentnosti označuje jako nejistá.`,
  ),
};

export const ARNOLD_HISTORICAL_DOCS = {
  coreTrainingRoutine: L(
    `Historical documentation note: the following reconstructs publicly reported training templates from Arnold Schwarzenegger's Gold's Gym / Muscle Beach years. It is educational history, not a prescription.

The most consistently reported structure from Schwarzenegger's competitive peak (roughly the late 1960s through the mid-1970s, training alongside Franco Columbu, Frank Zane, Dave Draper, and Ed Corney) was a six-day double-split week: training twice daily, six days a week, with each bodypart hit twice across the week rather than once. A common pairing widely referenced in Golden Era retrospectives and Schwarzenegger's own later writing was chest and back on one axis, shoulders and arms on another, and legs trained on their own days — each muscle group receiving a morning session and a separate afternoon session.

Volume, by contemporary standards, was extreme. Retrospective accounts describe 20 to 30-plus total working sets per major muscle group across the week, built from five or six exercises per bodypart rather than two or three. A typical chest session, as described in period interviews and Pumping Iron-era footage, might move through barbell bench press, incline dumbbell press, dips, and multiple angles of flye or cable work, with rep ranges commonly cited in the 6-to-10 zone on compound lifts and higher on isolation and pump-focused finishers. Supersets and giant sets (three or more exercises performed back-to-back with minimal rest) were a defining feature, along with training-partner-assisted forced reps and negatives once a set reached failure.

Arms and calves reportedly received disproportionate attention. Schwarzenegger has spoken publicly about calves being a stubborn point that required near-daily direct work, and arm training was folded into multiple sessions across the week rather than isolated to a single day. The broader philosophy, repeated across interviews from this period, was described as "instinctive training" — adjusting exercise selection and volume week to week based on how a muscle group was responding, rather than following a single rigid template for an entire competitive season. Rest periods between sets were kept short by modern powerlifting standards, generally cited around 45 to 60 seconds, consistent with the era's emphasis on maintaining a pump and training density over pure strength expression. This was, by every public account, a hypertrophy-first system built around volume, frequency, and constant variation rather than percentage-based intensity programming.

Back training, as documented in Pumping Iron footage and later interviews, reportedly paired heavy compound pulling — deadlifts on occasion, barbell rows, and wide-grip pull-ups or pulldowns — with cable and machine finishing work, again organized into supersets with chest on the same training day. Training partners were a documented structural feature rather than an incidental detail: Franco Columbu in particular is repeatedly cited across interviews as pushing Schwarzenegger through forced reps once a set reached failure, and the competitive, needling dynamic between training partners is described in multiple retrospectives as a deliberate psychological tool for extending sets beyond what either athlete would have reached alone. Shoulder and arm days reportedly combined barbell and dumbbell pressing for the deltoids with multiple curl and pushdown variations for biceps and triceps, again performed as supersets to keep density high across a short session.

Cardiovascular work was reportedly minimal to absent during this off-season mass-building phase, consistent with the sport's priorities of that era, with conditioning treated as a contest-prep concern rather than a year-round habit. It is worth noting that a later commercial product built around Schwarzenegger's name repackaged some of these general principles into a structured programme decades after his competitive career ended; that later commercial material is a separate, distinctly branded product and is not treated here as primary historical evidence of what Schwarzenegger actually did in the gym during his own competitive years.`,
    `Poznámka k historické dokumentaci: následující text rekonstruuje veřejně reportované tréninkové šablony z let Arnolda Schwarzeneggera v Gold's Gym / Muscle Beach. Jde o vzdělávací historii, ne o předpis.

Nejkonsistentněji reportovaná struktura z vrcholu jeho soutěžní kariéry (zhruba konec 60. let až polovina 70. let, trénink vedle Franca Columbu, Franka Zanea, Davea Drapera a Eda Corneyho) byl šestidenní double-split: trénink dvakrát denně, šest dní v týdnu, každá partie 2× týdně místo jednou. Běžné párování v retrospektivách Zlaté éry i v pozdějších Arnoldových textech: hrudník a záda na jedné ose, ramena a paže na druhé, nohy ve vlastních dnech — každá skupina ranní i odpolední jednotku.

Objem byl podle dnešních standardů extrémní. Retrospektivy popisují 20–30+ pracovních sérií na hlavní partii týdně z pěti až šesti cviků, ne ze dvou tří. Typická chest jednotka (dobové interview a footage z éry Pumping Iron) mohla jít přes bench press, incline dumbbell press, dips a více úhlů flye/cable, s opakováními často 6–10 na compoundech a vyššími na izolacích a pump finisherech. Supersety a giant sety (3+ cviky back-to-back s minimálním odpočinkem) byly definující rys, spolu s forced reps a negativy s partnerem po selhání.

Paže a lýtka reportovaně dostávaly neúměrnou pozornost. Arnold veřejně mluvil o lýtkách jako o tvrdohlavém místě s téměř denní přímou prací; paže byly rozprostřené do více jednotek týdně. Širší filozofie se popisovala jako „instinctive training“ — týdenní úpravy výběru a Objemu podle reakce partie, ne jedna rigidní šablona na celou sezónu. Odpočinky mezi sériemi byly krátké (běžně ~45–60 s) — důraz na pump a hustotu před čistou silou. Veřejný účet: Hypertrofie first — Objem, Frekvence, konstantní variace, ne procentuální Intenzita silového trojboje.

Záda (Pumping Iron + pozdější interview) reportovaně párovala těžké compound tahy — občas Mrtvý tah, barbell rows, wide-grip pull-upy/pulldowny — s cable/machine finishery, opět v supersetu s hrudníkem tentýž den. Tréninkoví partneři byli strukturální prvek: Franco Columbu je opakovaně citován jako ten, kdo táhl forced reps po selhání; soutěživá dynamika partnerů je popisována jako záměrný psychologický nástroj pro prodloužení sérií. Dny ramen a paží kombinovaly barbell/dumbbell tlaky na delty s curl a pushdown variantami, opět jako supersety pro hustotu v krátké jednotce.

Kardio bylo v off-season mass fázi reportovaně minimální až nulové — kondice jako contest-prep, ne celoroční zvyk. Pozdější komerční produkt kolem Arnoldova jména zabalil část principů do strukturovaného programu desítky let po kariéře; ten materiál je samostatný brandovaný produkt a není zde primární historickou evidencí toho, co Arnold skutečně dělal v posilovně ve svých soutěžních letech.`,
  ),
  documentedNutritionalApproach: L(
    `Historical documentation note: the following reconstructs publicly reported dietary patterns from Arnold Schwarzenegger's competitive bodybuilding years. It is educational history, not a prescription.

Public accounts of Schwarzenegger's Golden Era eating are less granular than modern macro-tracked bodybuilding diets, but several patterns recur across interviews and retrospectives. A large, protein-dense breakfast is the most frequently repeated detail — steak and eggs is the combination most consistently cited in period profiles and later career interviews describing his early training years. Beyond that anchor meal, the broader pattern described was five to six meals across the day, built around whatever high-protein whole foods were practically available to a bodybuilder training and living in that era: meat, eggs, dairy, and simple carbohydrate sources like potatoes and rice.

Supplementation existed but looked nothing like the modern whey-isolate market. Protein was supplemented in some periods through milk-and-egg-powder blends rather than the refined, fast-digesting powders available today, and the broader supplement culture of Golden Era Southern California gyms was informal compared to contemporary sports-nutrition science. Carbohydrate and water manipulation ahead of competition — a highly dialed science in modern contest prep — was, by most public accounts, considerably less precise in this era; competitors relied more on subjective mirror checks and experience than on structured peak-week protocols.

It is worth being explicit about the limits of this record: exact daily calorie or gram targets are not consistently documented across sources, and figures repeated in bodybuilding folklore vary depending on which interview or era is being quoted. What is consistently reported is the eating frequency (multiple meals daily), the protein emphasis (large portions of meat and eggs at nearly every meal), and the general absence of the calorie-counting precision that later became standard in the sport. Readers should treat any specific gram or calorie figure attributed to this period as an approximation drawn from athlete recollection decades after the fact, not a verified nutritional record, and should not treat an elite competitive bodybuilder's reported intake from this era as a template for their own eating.

Schwarzenegger's own later writing also draws a contrast between the more restrained, agriculturally simple eating of his Austrian upbringing and the comparatively food-abundant Southern California bodybuilding culture he entered as a young athlete, framing the adjustment to large-volume American eating as itself part of his early training story. Pre-contest carbohydrate and water adjustments in this era are described in general terms — reducing starchy carbohydrates and manipulating water intake in the days before a show — but without the precise, staged water-and-sodium protocols that later became standard in professional bodybuilding contest prep. Processed sugar is generally described as being minimized rather than eliminated, consistent with an era that had far less packaged "diet food" infrastructure than exists today. Multiple later interviews reinforce the same basic shape of the story across decades, which is part of why the broad pattern (frequent meals, meat-and-egg protein anchors, modest and imprecise contest-week manipulation) is treated here as reasonably well corroborated, even though exact numbers are not.`,
    `Poznámka k historické dokumentaci: následující text rekonstruuje veřejně reportované stravovací vzorce ze soutěžních let Arnolda Schwarzeneggera. Jde o vzdělávací historii, ne o předpis.

Veřejné účty stravování ze Zlaté éry jsou méně granulární než moderní makro-tracked diety, ale několik vzorců se opakuje. Velká, proteinově hustá snídaně je nejčastější detail — steak and eggs je kombinace nejkonsistentněji citovaná v dobových profilech i pozdějších interview o raných letech. Nad rámec kotvy: pět až šest jídel denně z prakticky dostupných high-protein foodů — maso, vejce, mléčné výrobky, jednoduché sacharidy (brambory, rýže).

Suplementace existovala, ale nevypadala jako dnešní whey-isolate trh. Protein se v některých obdobích doplňoval směsmi mléčného a vaječného prášku, ne rafinovanými rychlými prášky; kultura suplementů v posilovnách Southern California Zlaté éry byla neformální oproti dnešní sportovní nutriční vědě. Manipulace se sacharidy a vodou před závodem — dnes vysoce dialovaná věda contest prepu — byla podle většiny účtů výrazně méně přesná; závodníci spoléhali na zrcadlo a zkušenost spíš než na strukturované peak-week protokoly.

Limity záznamu je třeba říct nahlas: přesné denní kalorie nebo gramy nejsou napříč zdroji konzistentně dokumentované a folklórní čísla se liší podle interview a éry. Konzistentně reportovaná je frekvence jídel (více jídel denně), důraz na protein (velké porce masa a vajec skoro u každého jídla) a absence kalorického počítání, které se stalo standardem později. Jakékoli konkrétní gramy/kalorie z této éry ber jako aproximaci ze vzpomínek desítky let poté — ne jako ověřený nutriční log — a ne jako šablonu pro vlastní stravu.

Arnoldovy pozdější texty kontrastují skromnější, zemědělsky jednoduché stravování z rakouského dětství s potravinově bohatou kulturistickou kulturou Southern California. Předsoutěžní úpravy sacharidů a vody jsou popsané obecně — méně škrobů, manipulace s vodou ve dnech před show — bez přesných stupňovaných protokolů vody a sodíku moderního pro contest prepu. Zpracovaný cukr se spíš minimalizoval než eliminoval. Více pozdějších interview drží stejný základní tvar příběhu napříč desetiletími — proto široký vzorec (častá jídla, meat-and-egg protein kotvy, skromná a nepřesná contest-week manipulace) bereme jako přiměřeně doložený, i když přesná čísla ne.`,
  ),
};
