/**
 * Historical documentation bodies — Legendary Training Methods (Prompt: historical routines/diets).
 *
 * These entries reconstruct publicly reported training templates and dietary
 * patterns for well-known strength athletes and coaching systems. They are
 * framed strictly as historical documentation of what has been publicly
 * reported in interviews, documentaries, competition coverage, and long-running
 * coaching literature — not as medical advice, not as an official or licensed
 * reproduction of any athlete's proprietary programme, and not as an
 * instruction for a reader to copy the loads, calories, or bodyweight of an
 * elite competitor. The Strongest holds no affiliation with, and does
 * not claim endorsement from, any athlete named below. Where public evidence
 * is thin or inconsistent across sources, the text says so directly rather
 * than inventing specificity.
 */

export type HistoricalDocumentationBodies = {
  coreTrainingRoutine: string;
  documentedNutritionalApproach: string;
};

export const HISTORICAL_DOCUMENTATION_BY_SLUG: Record<
  string,
  HistoricalDocumentationBodies
> = {
  "arnold-schwarzenegger-golden-era-volume": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training templates from Arnold Schwarzenegger's Gold's Gym / Muscle Beach years. It is educational history, not a prescription.

The most consistently reported structure from Schwarzenegger's competitive peak (roughly the late 1960s through the mid-1970s, training alongside Franco Columbu, Frank Zane, Dave Draper, and Ed Corney) was a six-day double-split week: training twice daily, six days a week, with each bodypart hit twice across the week rather than once. A common pairing widely referenced in Golden Era retrospectives and Schwarzenegger's own later writing was chest and back on one axis, shoulders and arms on another, and legs trained on their own days — each muscle group receiving a morning session and a separate afternoon session.

Volume, by contemporary standards, was extreme. Retrospective accounts describe 20 to 30-plus total working sets per major muscle group across the week, built from five or six exercises per bodypart rather than two or three. A typical chest session, as described in period interviews and Pumping Iron-era footage, might move through barbell bench press, incline dumbbell press, dips, and multiple angles of flye or cable work, with rep ranges commonly cited in the 6-to-10 zone on compound lifts and higher on isolation and pump-focused finishers. Supersets and giant sets (three or more exercises performed back-to-back with minimal rest) were a defining feature, along with training-partner-assisted forced reps and negatives once a set reached failure.

Arms and calves reportedly received disproportionate attention. Schwarzenegger has spoken publicly about calves being a stubborn point that required near-daily direct work, and arm training was folded into multiple sessions across the week rather than isolated to a single day. The broader philosophy, repeated across interviews from this period, was described as "instinctive training" — adjusting exercise selection and volume week to week based on how a muscle group was responding, rather than following a single rigid template for an entire competitive season. Rest periods between sets were kept short by modern powerlifting standards, generally cited around 45 to 60 seconds, consistent with the era's emphasis on maintaining a pump and training density over pure strength expression. This was, by every public account, a hypertrophy-first system built around volume, frequency, and constant variation rather than percentage-based intensity programming.

Back training, as documented in Pumping Iron footage and later interviews, reportedly paired heavy compound pulling — deadlifts on occasion, barbell rows, and wide-grip pull-ups or pulldowns — with cable and machine finishing work, again organized into supersets with chest on the same training day. Training partners were a documented structural feature rather than an incidental detail: Franco Columbu in particular is repeatedly cited across interviews as pushing Schwarzenegger through forced reps once a set reached failure, and the competitive, needling dynamic between training partners is described in multiple retrospectives as a deliberate psychological tool for extending sets beyond what either athlete would have reached alone. Shoulder and arm days reportedly combined barbell and dumbbell pressing for the deltoids with multiple curl and pushdown variations for biceps and triceps, again performed as supersets to keep density high across a short session.

Cardiovascular work was reportedly minimal to absent during this off-season mass-building phase, consistent with the sport's priorities of that era, with conditioning treated as a contest-prep concern rather than a year-round habit. It is worth noting that a later commercial product built around Schwarzenegger's name repackaged some of these general principles into a structured programme decades after his competitive career ended; that later commercial material is a separate, distinctly branded product and is not treated here as primary historical evidence of what Schwarzenegger actually did in the gym during his own competitive years.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns from Arnold Schwarzenegger's competitive bodybuilding years. It is educational history, not a prescription.

Public accounts of Schwarzenegger's Golden Era eating are less granular than modern macro-tracked bodybuilding diets, but several patterns recur across interviews and retrospectives. A large, protein-dense breakfast is the most frequently repeated detail — steak and eggs is the combination most consistently cited in period profiles and later career interviews describing his early training years. Beyond that anchor meal, the broader pattern described was five to six meals across the day, built around whatever high-protein whole foods were practically available to a bodybuilder training and living in that era: meat, eggs, dairy, and simple carbohydrate sources like potatoes and rice.

Supplementation existed but looked nothing like the modern whey-isolate market. Protein was supplemented in some periods through milk-and-egg-powder blends rather than the refined, fast-digesting powders available today, and the broader supplement culture of Golden Era Southern California gyms was informal compared to contemporary sports-nutrition science. Carbohydrate and water manipulation ahead of competition — a highly dialed science in modern contest prep — was, by most public accounts, considerably less precise in this era; competitors relied more on subjective mirror checks and experience than on structured peak-week protocols.

It is worth being explicit about the limits of this record: exact daily calorie or gram targets are not consistently documented across sources, and figures repeated in bodybuilding folklore vary depending on which interview or era is being quoted. What is consistently reported is the eating frequency (multiple meals daily), the protein emphasis (large portions of meat and eggs at nearly every meal), and the general absence of the calorie-counting precision that later became standard in the sport. Readers should treat any specific gram or calorie figure attributed to this period as an approximation drawn from athlete recollection decades after the fact, not a verified nutritional record, and should not treat an elite competitive bodybuilder's reported intake from this era as a template for their own eating.

Schwarzenegger's own later writing also draws a contrast between the more restrained, agriculturally simple eating of his Austrian upbringing and the comparatively food-abundant Southern California bodybuilding culture he entered as a young athlete, framing the adjustment to large-volume American eating as itself part of his early training story. Pre-contest carbohydrate and water adjustments in this era are described in general terms — reducing starchy carbohydrates and manipulating water intake in the days before a show — but without the precise, staged water-and-sodium protocols that later became standard in professional bodybuilding contest prep. Processed sugar is generally described as being minimized rather than eliminated, consistent with an era that had far less packaged "diet food" infrastructure than exists today. Multiple later interviews reinforce the same basic shape of the story across decades, which is part of why the broad pattern (frequent meals, meat-and-egg protein anchors, modest and imprecise contest-week manipulation) is treated here as reasonably well corroborated, even though exact numbers are not.`,
  },

  "tom-platz-extreme-leg-training": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training templates associated with Tom Platz's leg-training reputation. It is educational history, not a prescription.

Platz's leg sessions are among the most frequently referenced single-bodypart routines in bodybuilding history, largely because of surviving training footage and repeated interview retellings. The publicly documented picture describes leg day as a standalone, extremely long session — commonly cited as lasting over an hour of continuous work — built around squats as the central movement, followed by hack squats, leg presses, and leg extensions or leg curls, frequently supersetted together rather than performed as isolated straight sets.

The squat portion is the most mythologized element. Interviews and footage reference Platz working through an extended warm-up pyramid before reaching working sets loaded with plates commonly described as reaching roughly eight per side (in the region of 400-plus pounds) for multiple repetitions, alongside separately documented high-repetition "breathing squat" style sets at lighter loads for 20 or more continuous reps — a method with roots in an earlier generation of strength training that Platz is publicly associated with popularizing within bodybuilding circles. Depth was consistently described as full range of motion, a trait often attributed in interviews to a gymnastics background that gave him unusual hip and ankle mobility under load.

Total set counts for the session are widely cited in the range of 20 or more hard sets across all leg exercises combined, with drop sets, partial-rep "burns," and forced reps at the end of nearly every set once a target rep count was reached. Leg extensions and leg curls were reportedly used both as pre-exhaustion tools before compound lifts and as finishers afterward. Because a single leg session absorbed this much volume and intensity, publicly reported frequency was low — legs trained roughly once, occasionally twice, per week — with far lower density training elsewhere in the split to allow recovery from what interviewers and training partners alike have described as an unusually punishing single day.

The high-repetition breathing-squat style sets Platz is publicly associated with trace back to an older strength-training tradition that predates modern bodybuilding, and interviewers have repeatedly connected his interest in that method to his own background in gymnastics, which he has cited in interviews as the source of the unusual ankle and hip mobility that let him squat to a genuinely full depth under heavy load without the technical breakdown that ends most lifters' sets far earlier. Calves are also frequently mentioned in retrospectives as receiving disproportionate direct attention on the same day, trained to failure with high reps immediately after the primary squat-and-machine sequence, consistent with the general Golden Era pattern of treating stubborn muscle groups with near-daily or same-day extra volume.

Hack squats and leg presses, the two movements most consistently named alongside barbell squats in surviving footage, were reportedly used at very high reps to extend the metabolic stress of the session once the heaviest barbell work was complete, rather than as a second maximal-strength stimulus. This ordering — heaviest, most technical lift first, followed by machine-based, higher-rep, higher-fatigue work — is a structural detail repeated consistently enough across interviews and footage that it is treated here as reasonably well documented, distinct from more speculative claims about exact weekly set totals that vary depending on which retrospective account is consulted.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns associated with Tom Platz's competitive years. It is educational history, not a prescription.

Public documentation of Platz's eating is considerably thinner than the documentation of his training, and this section should be read with that limitation in mind. The recurring theme across the interviews and retrospectives that do exist is a straightforward caloric surplus aimed at supporting both overall mass and the exceptional recovery demand created by his leg-training volume. Multiple meals per day — generally cited around five to six — appear consistently, built around era-typical bodybuilding staples: meat and eggs for protein, and rice, potatoes, and other starches for the carbohydrate load needed to fuel repeated high-volume squat sessions.

Some retrospective accounts emphasize a relatively high carbohydrate intake specifically in the context of leg-day recovery, framing food as fuel for the next punishing session rather than a finely periodized bulking or cutting cycle. This is consistent with the broader Golden Era pattern of less scientifically structured nutrition compared to the macro-tracked, contest-prep-periodized approach that became standard in bodybuilding decades later.

What is not well documented is a precise gram or calorie breakdown attributable specifically to Platz, contest-to-contest dietary changes, or a clearly sourced pre-competition cutting protocol. Where popular fitness media has attached specific numbers to his diet, those figures are generally not traceable to a primary interview and should be treated as folklore rather than verified history. This entry is deliberately conservative for that reason: the honest historical record supports "high-calorie, high-carbohydrate, multiple meals daily, food as recovery fuel for extreme leg volume" as a pattern, but does not support precise macro reconstruction, and readers should not treat any specific number attached to this pattern elsewhere online as a verified historical fact.

Later-career interviews and podcast appearances, given decades after his competitive peak, add some retrospective colour but generally reinforce rather than sharpen the historical record — Platz has spoken about the sheer logistical effort of eating enough food to recover from his own leg sessions, framing food intake explicitly as a recovery necessity dictated by training demand rather than a separately engineered nutritional strategy. Hydration and general food volume around leg day specifically are mentioned in these retrospectives as being deliberately increased in the day or two surrounding the session, consistent with the broader described pattern of eating as fuel for an unusually demanding single training day rather than a evenly distributed weekly plan. No independently documented source describes a formal pre-contest peak-week protocol attributable to Platz with the same specificity available for some of his competitive peers, and this profile does not manufacture one.

Platz has also spoken in later interviews about the contrast between his own comparatively simple, high-volume eating approach and the more scientifically periodized contest-prep protocols that emerged in the sport after his own competitive years, framing his era's nutrition as generally more intuitive and less data-driven than what became standard practice for professional bodybuilders decades later. This self-aware framing is useful historical context: it suggests the absence of granular macro documentation for this period is not merely a gap in the historical record but partly reflects that this level of dietary precision was not yet common practice within bodybuilding at the time, even at an elite competitive level. Readers should weigh that context when comparing Platz's documented eating pattern to the far more exhaustively tracked diets of modern competitive bodybuilders.`,
  },

  "ronnie-coleman-heavy-high-volume-training": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training templates from Ronnie Coleman's competitive bodybuilding years. It is educational history, not a prescription.

Coleman's training is unusually well documented on video, since a large volume of his gym sessions were filmed and commercially released across his career, giving this profile a stronger visual evidence base than most Golden Era comparisons. The recurring split across publicly available footage and interviews follows a five-to-six-day rotation: chest and triceps, back and biceps, shoulders, legs, and a further arm-focused or repeat day, cycling through the week with limited full rest.

What sets Coleman's documented approach apart from most bodybuilding history is the combination of powerlifting-level absolute loads with bodybuilding rep ranges and volume. Publicly filmed sessions show him squatting with approximately 800 pounds, performing dumbbell bench presses with roughly 200-pound dumbbells for multiple reps, and barbell rowing loads commonly cited around 365 pounds for sets — numbers that were unprecedented for a competitive bodybuilder rather than a dedicated powerlifter, and which are corroborated by widely circulated gym footage rather than resting on interview claims alone. Rep ranges on these primary compound lifts are generally documented in the 6-to-12 zone even at near-maximal loads, followed by isolation work at higher reps to complete each session's volume target.

Training intensity on these lifts, evident from the footage's audio, was maximal in both load and psychological arousal — the widely recognized "Yeah buddy!" and "Lightweight, baby!" cues were not marketing invention but genuine in-session vocalizations captured during near-limit attempts. Coleman also famously maintained this training volume while working full-time as a police officer for much of his competitive career, reportedly training in early morning or late-night sessions around shift work — a detail repeated across interviews as a testament to the discipline behind the filmed intensity, though it is also cited by Coleman himself in later years as a contributing factor to the severe hip and spinal injuries that followed his competitive retirement.

Exercise selection within each session is unusually well documented compared to most Golden Era athletes precisely because so much of it was filmed rather than only described after the fact. Chest sessions commonly show barbell and machine pressing at heavy loads followed by isolation work; back sessions pair heavy barbell and T-bar rows with wide pulldown or pull-up variations; leg day, documented across multiple filmed sessions, shows the widely cited near-800-pound squat performed with a spotting team, followed by leg press and leg extension work at high volume. A later documentary released after his run of injuries and surgeries revisited this footage directly, with Coleman himself reflecting on the accumulated cost of training at that intensity and volume for over a decade — a piece of primary, athlete-sourced retrospective evidence that this profile treats as directly relevant context alongside the earlier, more triumphant footage.

Rest periods and session length are less precisely documented than the load and rep data, since footage tends to be edited for highlight value rather than showing full real-time sessions, so this profile does not assign a specific rest-interval figure with the same confidence as the load numbers, which are directly visible and repeatedly corroborated across multiple video sources.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns from Ronnie Coleman's competitive bodybuilding years. It is educational history, not a prescription.

Coleman's off-season eating is one of the more consistently cited caloric intakes in bodybuilding media, with figures in interviews and profile pieces commonly falling somewhere in a very wide 5,000-to-8,000-plus calorie range depending on which point in his career and which source is quoted — a spread that itself signals the figure was never precisely tracked in the way modern coached bodybuilders track intake, but rather estimated after the fact. The consistently reported structure was five to six meals daily, built around high-protein staples repeatedly named in interviews: chicken breast, egg whites, lean steak, and cottage cheese, paired with complex carbohydrate sources including rice, oats, and sweet potato.

Supplement shakes were reportedly used to help hit the volume of food required to sustain his off-season mass, given the practical difficulty of eating whole-food meals of that size six times a day. Contest preparation, by contrast, involved a reported reduction in both calories and carbohydrates alongside increased cardiovascular work, following the standard bodybuilding contest-prep pattern of the era, though the exact reduction — in percentage or absolute terms — is not consistently documented across sources and appears to have varied contest to contest.

This entry is deliberately cautious about precision: while the general shape of Coleman's documented eating (very high off-season calories, high protein, structured meal frequency, reduced intake during contest prep) is consistently repeated across independent interviews, exact macro splits are not part of the verifiable public record to the same degree as his training footage is. Coleman's later-life health struggles, including multiple spinal surgeries, have also been publicly connected by Coleman himself to the combined stress of his training loads and the scale of eating and body mass this diet was built to sustain — a detail that belongs in any honest historical account of this period.

Public reporting also references a cheat-meal culture typical of the era's off-season approach, with less rigid adherence week to week outside of contest-prep windows, though specific frequency or content of these meals is not documented with the precision available in modern coached bodybuilding. Coleman later built a commercial supplement business drawing on his competitive reputation; that later commercial venture is a separate branded enterprise and is treated here only as context, not as primary historical evidence of what he actually ate during his competitive years. Bodyweight figures during his most dominant Mr. Olympia seasons are documented in competition programme materials and contemporaneous magazine coverage, giving reasonable confidence to the general scale of mass this eating pattern was built to support, even where the day-to-day food log itself was never formally published.`,
  },

  "eddie-hall-500kg-deadlift": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training templates from Eddie Hall's build toward the 2016 500 kg deadlift. It is educational history, not a prescription.

The centrepiece of Hall's publicly described preparation was a weekly deadlift emphasis built around alternating heavy and speed-oriented weeks rather than maximal pulling every session. In a contemporaneous interview shortly after the lift, Hall described training the deadlift roughly once per week, with heavy weeks pyramiding up in load across a small number of hard sets, and lighter "speed" weeks moving loads reported around half of his working max as fast as possible off the floor. The stated purpose of the speed weeks was to reinforce first-pull explosiveness — the phase from the floor to the knee, where Hall repeatedly described momentum being won or lost — rather than to grind through slow maximal reps every session.

A reported readiness marker roughly three weeks before the competition lift was a fast pull at approximately 450 kilograms, framed in his own account as around 90 percent of the eventual 500 kg target; hitting that marker with visible bar speed reportedly signalled that no further heavier training pulls were necessary before the attempt itself. Supporting work referenced in interviews included heavy leg-press training, which Hall has publicly credited as a major contributor to his leg-drive off the floor, alongside upper-back and pulling accessory work to support grip and posture under load.

Crucially, this deadlift-specific work sat inside a full strongman training calendar rather than replacing it — Hall has been public about continuing yoke, farmer's carry, atlas stone, and other event-specific training throughout the same period, since the 500 kg attempt overlapped with a broader World's Strongest Man campaign rather than standing as an isolated single-lift project. Publicly available training footage from this era, while extensive, does not amount to a complete disclosed weekly programme, and this profile does not claim to reproduce Hall's full proprietary training plan — only the principles he has described in his own words across multiple interviews.

The competition context matters to the historical record: the 500 kg pull took place on 9 July 2016 at the World Deadlift Championships, contested during Giants Live's Europe's Strongest Man event in Leeds, under strongman-specific equipment rules that permitted supportive gear including lifting straps and a deadlift suit — a meaningfully different equipment context from raw or single-ply powerlifting deadlift records, and one this profile keeps explicit rather than letting readers assume a like-for-like comparison. Warm-up structure on heavy training days, as described in interview material, reportedly built through a long pyramid of increasing loads before reaching the day's top sets, consistent with standard heavy-pull practice at that level rather than describing anything unusual to Hall specifically.

Total weekly training frequency across the full strongman calendar, combining deadlift-specific sessions with event practice and general strength work, is reported in the general range of five to six sessions per week during peak preparation, though Hall has not published a formal disclosed schedule with day-by-day specificity, so this profile treats the weekly frequency figure as an approximate characterization drawn from multiple interviews rather than a verified fixed schedule.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns from Eddie Hall's peak strongman years. It is educational history, not a prescription.

Hall's eating during his strongman competitive peak is one of the most widely reported extreme intakes in modern strength sport, with interviews and profile pieces from around the 500 kg period commonly citing a daily intake in the region of 10,000 calories. Publicly described meals from this era include very large steak dinners, high volumes of whole milk, and frequent protein shakes layered on top of standard meals, reflecting the scale of eating required to sustain a competition bodyweight commonly reported around 197 kilograms at his strongman peak.

This intake was explicitly framed, in Hall's own later interviews, as a means to an end rather than a sustainable lifestyle — food as fuel for an extreme, short-lived athletic goal rather than a template for ordinary training. That framing has become more explicit over time: Hall's post-strongman public journey, including a widely covered and dramatic weight loss ahead of a televised boxing match against fellow strongman Hafthor Björnsson, involved shedding a large proportion of that competition bodyweight and has been described by Hall himself as evidence of how extreme and ultimately costly the bulking diet had become for his long-term health.

Exact macronutrient breakdowns from the 500 kg era are not part of the well-documented public record; the widely repeated 10,000-calorie figure is best treated as an approximate, interview-derived characterization of scale rather than a precise tracked number. What is consistently and reliably documented is the direction of travel — extremely high food volume to support extreme bodyweight and strongman-specific force output during the competitive peak, followed by a well-publicized and dramatic reversal once that specific athletic goal was no longer the priority. Ordinary readers should treat both ends of this documented history as illustrations of elite-context extremity, not as dietary targets to copy in either direction.

A later-released documentary following Hall's post-strongman career, including his transition toward mixed martial arts and boxing, publicly documented significant further bodyweight and lifestyle changes beyond the initial boxing-match weight cut, reinforcing that the 500 kg-era eating pattern was explicitly tied to that specific competitive chapter of his career rather than representing a fixed lifelong approach. Hall has also spoken publicly in multiple interviews about digestive and general health difficulties he attributes to the sheer food volume required at his strongman peak, framing the historical diet, in his own retrospective words, as something he would not repeat outside of a specific competitive goal. This profile treats those retrospective athlete comments as directly relevant historical context rather than omitting them in favour of only the more dramatic peak-era figures.

Contemporaneous 2016-era interview coverage also references a supplement regimen layered on top of whole-food meals, consistent with the broader strongman-competitor pattern of using shakes and powders to close the gap between practical whole-food eating capacity and the very high total calorie target being pursued, though specific brands or exact supplement dosages are not part of the well-documented public record and are not reconstructed here. Meal timing around the heaviest training days is referenced only in general terms across available interviews — larger meals surrounding heavy sessions to support recovery — rather than through a disclosed hour-by-hour eating schedule, and this profile does not invent that level of granularity where the primary sources do not support it.`,
  },

  "hafthor-bjornsson-strongman-strength": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training templates from Hafthor Björnsson's strongman and powerlifting years. It is educational history, not a prescription.

Björnsson's documented training history spans two distinct, well-covered phases. The first is a long strongman career built in Iceland, much of it at his own training facility alongside a documented circle of training partners, combining heavy log press, axle press, atlas stone loading, yoke carries, and farmer's walks across a rotating weekly schedule typical of top-level strongman competitors — high exercise variety by design, since World's Strongest Man-style competition rewards broad event capability rather than single-lift specialization.

The second, more tightly documented phase is the dedicated deadlift specialization block that preceded his May 2020 deadlift of 501 kilograms, at the time recognized as an official world record and covered extensively by strength-sport and mainstream media alike, alongside a released training documentary following the buildup. Public accounts of this period describe a marked shift away from broad strongman event training toward a narrower, powerlifting-style peaking structure focused on the squat, bench press, and above all the deadlift, with heavier and more frequent deadlift-pattern exposure than his general strongman training had historically featured, built specifically to peak one lift on one day rather than to maintain broad event fitness.

This specialization block is also publicly associated with a significant reported bodyweight and conditioning change compared to his peak strongman mass, reflecting a training emphasis shift toward maximal force in a single lift rather than sustained multi-event output. As with other elite peaking accounts in this profile, the publicly available documentary and interview material describes principles and a broad structural shift rather than disclosing a complete day-by-day proprietary programme, and this profile does not claim to reproduce that plan in full.

The publicly reported build toward the 501-kilogram pull describes a structured progression of training deadlifts over preceding months, with interview and documentary material referencing working loads climbing steadily toward the record attempt inside a dedicated peaking window, supported by a visible coaching and training-partner setup rather than solo training. Squat and bench press work continued through this period as supporting lifts rather than being dropped entirely, consistent with a powerlifting-style peaking block that still maintains the other competition lifts at reduced volume while the primary lift receives the bulk of peaking-phase attention. Equipment and setup — including strap use and a deadlift suit consistent with strongman-record conventions rather than raw powerlifting rules — were part of the documented record context, a distinction this profile keeps explicit given how often absolute deadlift numbers are compared across different equipment standards without noting the rule differences.

Earlier in his career, Björnsson's strongman training is documented mainly through event coverage and training-camp footage from his own facility rather than a single authoritative published programme, reflecting the sport's general pattern of less formalized public programme documentation compared to competitive powerlifting.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns from Hafthor Björnsson's strongman and post-strongman years. It is educational history, not a prescription.

Björnsson's strongman-era eating is publicly documented at the extreme end of competitive strength sport, with interviews from his competitive peak citing daily intakes reported as high as approximately 12,000 calories at points in his career, needed to sustain a competition bodyweight widely reported above 400 pounds (roughly 180-plus kilograms). As with comparable strongman-era accounts, this figure is best understood as an interview-derived approximation of scale rather than a precisely tracked macro target, and it varied across different points in a long competitive career rather than representing one fixed daily plan.

What makes Björnsson's documented dietary history particularly notable is the scale of contrast with a later, extensively covered chapter: his publicly documented weight cut ahead of a 2022 boxing match against Eddie Hall, in which mainstream sports and general media reported a loss in the range of 130 pounds from his strongman peak bodyweight, achieved through a sustained and heavily publicized calorie and training overhaul under professional boxing coaching and nutrition guidance. That transformation was covered extensively enough to be treated as reliable public history, even though granular week-by-week macro figures were not published in full.

Taken together, Björnsson's documented nutritional history illustrates two opposite, both extreme, applications of diet to a specific athletic goal: an enormous surplus to support world-class strongman force output, followed by an equally dramatic and well-documented deficit to support a boxing-appropriate physique and weight class. Neither extreme is presented here as guidance; both are historical illustrations of how elite athletes have publicly described manipulating intake for a specific, time-bound competitive purpose, under levels of coaching, monitoring, and physiological headroom that do not transfer to a general audience.

The boxing-prep weight cut is additionally notable for being one of the more professionally supervised transformations documented in this collection, publicly reported to have involved a dedicated nutrition and conditioning team working alongside boxing coaching staff over an extended multi-month timeline rather than a rapid or informal cut — a detail repeatedly emphasized in the surrounding media coverage precisely because of how large the total change was. Reporting around the deadlift specialization block that preceded the 501-kilogram record also references a leaner, more powerlifting-appropriate bodyweight compared to his heaviest strongman-era mass, suggesting his documented history includes at least three distinguishable dietary phases across his career — strongman bulk, deadlift-peaking recomposition, and boxing-specific cut — each publicly reported but none disclosed with full day-by-day nutritional detail.

Mainstream sports coverage of the boxing-prep transformation also documented visible changes in training conditioning alongside the dietary shift, framing the cut as a combined nutrition-and-training overhaul rather than a diet-only intervention, which is consistent with how professionally supervised weight-class transitions are generally reported across combat-sport media. Because the strongman-era calorie figures and the boxing-cut outcome are both documented mainly through interview and media estimate rather than a jointly published, verified nutrition log, this profile treats the overall shape of the transformation — extreme surplus followed by extreme, professionally supervised deficit — as reliable, while explicitly declining to state precise calorie or macro figures for either phase as verified fact.`,
  },

  "colton-engelbrecht-superheavyweight-powerlifting": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training patterns associated with Colton Engelbrecht's superheavyweight raw powerlifting career. It is educational history, not a prescription. Evidence here is honestly thinner and more contemporary than for legacy athletes covered elsewhere on this site — most of what is publicly known comes from Engelbrecht's own uploaded training footage and appearances on strength-sport podcasts and video interviews, rather than long-form independent journalism or decades of retrospective coverage.

Within that more limited evidence base, the recurring pattern documented across his own published training content is a raw superheavyweight approach built on frequent exposure to the three competition lifts — squat, bench press, and deadlift — with volume accumulation phases where working sets are performed at moderate-to-heavy loads across multiple sets, followed by a more compressed peaking phase closer to competition where volume drops and intensity rises toward openers and planned attempts. His own commentary in video content references training within a visible strength-sport gym community, with training partners and setup cues discussed specifically around the logistical demands of lifting at superheavyweight bodyweight — bar path, brace, and equipment considerations that differ somewhat from lighter-class lifters.

Because most of this record is self-published rather than independently verified, this profile is careful not to assign precise set-and-rep numbers with false confidence. What can be said with reasonable confidence is the broad shape: high-frequency touches on the big three lifts, a volume-then-peak periodization structure common across modern raw powerlifting, and public meet results that anchor the credibility of the underlying training, even where the session-by-session detail is not as exhaustively documented as it is for athletes with a longer public interview history.

As a modern superheavyweight competitor, Engelbrecht's documented public lifts include raw squat, bench, and deadlift numbers reported through recognized meet results and verified on competition leaderboards, which is the strongest and most independently checkable part of his public record. Around those results, his own uploaded training content shows accessory and technique-focused work supporting each of the three lifts — belt and brace cueing for the squat and deadlift given the technical demands of moving very heavy absolute loads, and pressing-specific accessory work supporting the bench — discussed by Engelbrecht himself in narrated training-video commentary rather than through third-party coaching disclosure. Meet-cycle structure, as described in his own content, follows the broadly standard raw powerlifting pattern of a longer volume-accumulation phase followed by a shorter, lower-volume peaking phase in the final weeks before a meet, a structural approach shared widely across the competitive raw powerlifting community rather than unique to him specifically.

Given the contemporary and largely self-authored nature of this record, this profile avoids reconstructing a specific weekly split with named exercises and set-and-rep prescriptions, since doing so would imply a level of independent verification that does not yet exist for this athlete's training history in the way it does for longer-documented figures elsewhere in this collection.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns associated with Colton Engelbrecht's superheavyweight competitive career. It is educational history, not a prescription. As with the training side of this profile, independent nutritional documentation is limited, and readers should weight this section's confidence accordingly.

The general theme repeated in Engelbrecht's own public commentary is a high-calorie, high-protein approach consistent with maintaining and building mass appropriate to the unlimited superheavyweight raw powerlifting class, where there is no weight ceiling incentivizing calorie restriction the way there is in lower or middle weight classes. Beyond that general theme, specific meal structures, gram targets, or meal timing are not part of a well-documented independent public record; most of what exists is self-reported through his own channels rather than corroborated by outside nutrition coaching disclosures or third-party reporting.

This profile deliberately avoids inventing specificity that does not exist in the public record. Where other entries in this collection can cite decades of repeated, cross-referenced interview detail, Engelbrecht's documented history is newer, thinner, and largely self-authored. The honest historical statement is simply this: publicly available commentary supports a high-calorie, high-protein, mass-supportive eating pattern typical of unlimited-class raw powerlifting, without the level of independently verified granular detail available for longer-tenured or more extensively interviewed athletes elsewhere in this collection.

Because the superheavyweight class carries no upper bodyweight limit, the competitive incentive structure that drives detailed weight-cutting documentation in lower and middle weight classes simply does not apply in the same way, which is itself a useful piece of context for readers trying to understand why this entry, and unlimited-class powerlifting nutrition generally, tends to be less granularly reported than weight-class-constrained sports. Engelbrecht's own content occasionally touches on general eating habits and food volume in narrated commentary, but without the kind of third-party nutrition-coaching disclosure, tracked macro breakdowns, or long-form magazine profile treatment that produced the more detailed historical record available for earlier-generation strength athletes in this collection. This profile treats that gap honestly rather than filling it with plausible-sounding invented numbers.

Where his own commentary does touch on food, it is generally in the context of explaining recovery between heavy training sessions rather than presenting a structured or named nutritional system, consistent with how many contemporary strength-sport content creators discuss eating informally through video rather than through a published or coached programme document. This profile also notes that Engelbrecht's competitive career is still active and ongoing as of this writing, meaning the public documentation base is likely to grow over time; the appropriately cautious approach here is to describe the honestly thin current record rather than to project future detail or to borrow specificity from unrelated superheavyweight athletes as if it applied to him directly. Any future independently verified nutrition-coaching disclosure would meaningfully change the confidence level of this entry, but no such disclosure is part of the record at present.`,
  },

  "john-haack-relative-strength": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training patterns associated with John Haack's competitive powerlifting career. It is educational history, not a prescription.

Haack built his public reputation less on outright weight-class-agnostic totals and more on an exceptionally high raw total relative to a competition bodyweight generally cited in the 198-to-220-pound range across his career, a framing repeated consistently across powerlifting podcast appearances and open-meet coverage. Publicly discussed training principles associated with his approach, drawn from long-form podcast interviews across the competitive powerlifting media ecosystem, emphasize frequent submaximal technical exposure to the competition lifts rather than constant one-rep-max testing — touching squat, bench, and deadlift patterns multiple times per week at moderate loads to reinforce technical consistency, with true maximal or near-maximal attempts reserved for defined peaking windows ahead of competition.

Autoregulation is a recurring theme in his publicly discussed approach: Haack has spoken in interviews about adjusting daily training loads based on rate-of-perceived-exertion feedback rather than following a rigid predetermined percentage chart every session, a method broadly associated with RPE-based programming that gained wide adoption across competitive powerlifting during the period of his rise. His training history across a long competitive career also included periods both self-coached and coached by others, meaning the specific program details discussed publicly vary somewhat by era rather than describing one single fixed system across his whole career.

Because much of this record lives in podcast conversation rather than published programme documents, this profile treats it as principle-level documentation: high-frequency technical touches, RPE-based load adjustment, and a periodized approach that separates volume-accumulation phases from meet-specific peaking, rather than claiming to reproduce any specific week-by-week template Haack has used.

Haack's public meet history across national and international raw powerlifting competition anchors the credibility of this general account, with multiple recognized-federation meet results forming the strongest, most independently verifiable layer of his documented record. Interview commentary also references periods of training at higher relative frequency for the squat and deadlift specifically, with lighter technical sessions placed between heavier or more fatiguing training days rather than a strict single-heavy-day-per-week structure, a pattern broadly consistent with the wider "high-frequency" school of thought that grew in popularity across competitive powerlifting during the same years his own competitive reputation was rising. Coaching relationships across his career are referenced in general terms in podcast conversation as having shifted over time between self-directed and externally coached periods, without a single named system being consistently attributed to his entire competitive history in independently verifiable detail.

Given the podcast-and-interview-heavy nature of this record, this profile stops short of reconstructing a specific numbered weekly template, since no single publicly disclosed programme document exists in the way it does for some other entries in this collection, and inventing one would overstate the confidence the public record actually supports.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns associated with John Haack's competitive powerlifting career. It is educational history, not a prescription.

Public nutritional documentation for Haack is noticeably thinner than the training-method documentation drawn from his podcast history, and this section should be read with that limitation clearly in mind. The recurring theme across available interview content is weight-class management rather than a specific named diet system — staying within striking distance of a chosen competitive class (discussion has touched on both 220-pound-region and heavier class considerations at different points in his career) while preserving the strength-to-bodyweight ratio that defines his public reputation as a relative-strength specialist.

Interview commentary references a generally disciplined but not extremely restrictive eating approach, consistent with a powerlifter prioritizing performance and recovery within a chosen weight class rather than pursuing an aesthetic-focused physique goal. Beyond that general framing, granular details such as specific meal counts, macro splits, or supplement protocols are not consistently documented across independent sources in the way that, for example, bodybuilding-era diets are documented through decades of magazine profiles.

This profile is intentionally conservative here: the honest public record supports "disciplined weight-class-conscious eating in service of relative strength" as a documented theme in Haack's own commentary, but it does not support a detailed reconstructed meal plan, and readers should treat any more specific numbers circulating in fan forums or secondary blogs as unverified rather than primary-sourced history.

What is somewhat more consistently referenced across his public commentary is the general trade-off at the centre of relative-strength competition: eating enough to support recovery from a demanding training frequency while staying close enough to a chosen weight class that his signature relative-strength numbers remain meaningful within that class's competitive context. Podcast conversation has touched on the mental and logistical challenge of that balance during longer competitive stretches, framed candidly as an ongoing management problem rather than a solved system, which is itself a useful piece of honest context distinguishing his public account from the more polished, retrospectively tidy diet narratives sometimes told by athletes further removed from their competitive years. No independently sourced macro breakdown or meal-by-meal plan attributed to Haack exists in the public record at the level of detail this profile would need to reconstruct one responsibly.

Discussion across powerlifting podcast appearances also touches on the general difficulty of comparing relative-strength performance across different bodyweights within a class, a framing that naturally keeps conversation focused on training and competitive strategy rather than on granular nutrition detail — which may partly explain why so much of the public record around Haack concerns programming philosophy while comparatively little concerns food. This profile treats that emphasis as reflective of the actual available source material rather than as an oversight to be corrected with invented specificity, and encourages readers interested in a more detailed historical diet reconstruction to look toward athletes in this collection, such as certain bodybuilders, for whom that level of documentation genuinely exists.`,
  },

  "jamal-browner-sumo-deadlift": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly reported training patterns associated with Jamal Browner's sumo deadlift specialization. It is educational history, not a prescription.

Browner's public profile is built substantially on self-published training footage, most visibly through video content produced with his brother, showing a deadlift-centric approach built around the sumo stance rather than conventional pulling. Publicly documented raw sumo deadlift performances cited in strength-sport media place his competition and training pulls in the region of 400 kilograms and above (commonly referenced around the 880-pound mark), performances that have been corroborated through footage from recognized raw powerlifting federation meets rather than resting on self-report alone.

The training content he and his training partners have published documents frequent deadlift-pattern exposure across the week rather than a single heavy pull day — including deficit deadlifts (pulling from an elevated platform to increase range of motion and starting-position demand), block pulls (partial range-of-motion pulls from a raised surface to overload the lockout portion), and banded variations intended to alter the strength curve through the lift. Squat volume is documented as a complementary, though secondary, component of the published training, used to support general leg and hip strength underneath the sumo-specific pulling work.

Because this documentation is substantially self-published rather than independently reported by outside journalists, this profile treats it with appropriate caution: the broad shape of high-frequency sumo-specific deadlift accessory work, corroborated by verified competition results, is reasonably well supported, while exact set-and-rep prescriptions attributed to Browner in secondary fan content should be treated as approximate interpretations of his published footage rather than a disclosed formal programme.

Browner's public meet history through recognized raw powerlifting federations provides an independently checkable anchor for the training claims made in his own content, distinguishing his record from athletes whose public profile rests entirely on self-reported gym footage without a verified competitive result attached. Published training videos also document a close working relationship with his brother as a consistent training partner across much of his publicly shared content, with shared cueing, spotting, and technical feedback forming a visible part of the training culture the channel presents. Squat training, while secondary to the sumo deadlift specialization in emphasis, is documented at meaningful volume in the same published sessions, framed in his own commentary as supporting general leg and hip strength that underpins sumo pulling technique rather than as a competing primary focus.

Given the self-published nature of the underlying evidence, this profile does not attempt to reconstruct a specific weekly split with precise set-and-rep numbers for Browner, since doing so would overstate the confidence the available public record actually supports relative to more thoroughly independently documented athletes elsewhere in this collection.

Coverage of Browner's raw sumo deadlift performances within the wider powerlifting media ecosystem has also generated broader public interest in sumo-specific specialization as a distinct approach within deadlift training more generally, distinguishing accessory selection (deficit pulls emphasizing the initial pull off the floor, and block pulls emphasizing lockout) that specifically address the biomechanical demands of a wide sumo stance rather than a conventional pulling stance. This distinction between conventional and sumo-specific accessory selection is a genuinely documented feature of his published training content and is treated here as a reasonably confident structural observation, even where the precise weekly dosage of each accessory movement remains undisclosed at the level of a formal programme document.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported dietary patterns associated with Jamal Browner's competitive powerlifting career. It is educational history, not a prescription.

Browner's publicly shared content includes meal-preparation-style videos referencing a high-calorie approach consistent with maintaining and building mass appropriate to the heavier raw powerlifting weight classes in which he has competed, built around large portions of rice and meat-based staples typical of strength-sport bulking content shared across social platforms. As with the training side of this profile, this material is self-published rather than independently verified by outside nutrition reporting, so specific gram or calorie targets should be understood as athlete-reported rather than third-party confirmed.

The general, more confidently stated pattern is straightforward: a mass-supportive, high-calorie eating approach aligned with competing in a heavier raw powerlifting class, documented primarily through the athlete's own shared content rather than through the kind of decades-spanning independent interview record available for older, more extensively profiled strength athletes elsewhere in this collection.

This profile deliberately does not attempt to reconstruct a precise meal-by-meal plan for Browner, since the underlying public evidence does not support that level of detail with confidence. Readers should treat this entry as a documented general pattern rather than a verified nutritional programme.

Published meal-prep content from his channel generally shows large-format, calorie-dense meals prepared in batches — a presentation style common across strength-sport social media aimed at demonstrating the practical logistics of eating at volume rather than at precisely communicating tracked macro targets to an audience. Where his own commentary does reference specific goals, it is generally framed around supporting training recovery and competition bodyweight within his chosen raw powerlifting class rather than around a named diet system or externally credentialed nutrition coaching programme. As with the training side of this entry, the honest documentation gap here is a function of the source material being contemporary, self-published, and social-media-native, rather than benefiting from the years of accumulated third-party interview and magazine coverage available for some other athletes in this collection, and this profile does not close that gap by inventing detail that is not actually part of the verifiable record.

The broader social-media strength-sport culture that Browner's content belongs to has, over the period of his rise to public prominence, generally normalized this kind of informal video-based nutrition documentation as an alternative to the longer-form interview and magazine profile format that produced more granular records for earlier-generation athletes; that shift in how athletes communicate publicly is itself part of the honest historical context for why this entry reads differently in structure and confidence level from, for example, the bodybuilding-era entries elsewhere in this collection, even though both are genuinely grounded in publicly available material.

Taken as a whole, the documented nutritional pattern for Browner is best summarized as calorie-abundant, protein-and-rice-centred eating in support of a heavier raw powerlifting weight class, communicated through the athlete's own social channels rather than through independently reported journalism, coached disclosure, or long-form retrospective interview — a genuinely different evidentiary category from several other entries in this collection, and one this profile flags plainly rather than papering over with confident-sounding but unverifiable specifics.`,
  },

  "boris-sheiko-russian-powerlifting": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly circulated structural principles of the Sheiko powerlifting system associated with coach Boris Sheiko's long career with Russian national powerlifting teams. It is educational history describing a coaching system, not a personal celebrity routine, and not a prescription.

The Sheiko system is unusual among the entries in this collection in that it is documented primarily through numbered training templates that have circulated widely among competitive powerlifters for years — commonly referred to informally within the sport as "Sheiko programs," associated with a family of numbered templates that grew out of his coaching work with Russian national-level lifters. The consistently reported structural signature of these templates is a four-times-per-week training frequency, with every session touching at least one, and often two, of the three competition lifts (squat, bench press, deadlift) or a close technical variant of them.

Rather than building sessions around a small number of maximal-effort sets, the publicly documented template family emphasizes high total weekly volume performed at predominantly submaximal loads — working percentages widely cited in the roughly 50-to-80 percent of one-rep-max range, spread across many sets of low-to-moderate reps within a session, so that total weekly tonnage on the competition lifts is very high even though individual set intensity rarely approaches a true maximum outside of planned testing weeks. Bench press in particular is documented as being trained multiple times within the same week across most template variants, reflecting a broader Russian and Soviet-era powerlifting culture that treated technical repetition at submaximal loads as the primary route to competition-day strength, rather than frequent maximal testing.

A generic weekly shape consistent with the widely shared template family looks roughly like: an early-week session combining squat and bench work, a mid-week session with a bench emphasis, a session combining deadlift and bench variants, and a later squat-and-bench session — with specific loads, rep schemes, and variant exercises changing systematically across a multi-week mesocycle that builds toward a tapered competition peak. This profile describes that general shape as it has been widely reported and shared within the sport, without claiming to reproduce any specific numbered template in full.

Within the widely shared template family, some numbered variants are specifically associated in lifting-community discussion with a bench-press specialization emphasis, reflecting the broader observation that bench press responds well to very high touch-frequency at submaximal loads — a principle that traces back to competitive weightlifting and powerlifting methodology broadly associated with Eastern Bloc sport-science traditions rather than being unique to any single coach. Close variant exercises documented across these templates include paused competition-style bench presses, close-grip and board-press variations, box squats and pause squats, and deficit or block-pull deadlift variants, each rotated systematically across a mesocycle rather than trained as a single fixed exercise for months at a time. Taper structure toward a competition, as documented across the widely shared templates, generally reduces total volume sharply in the final one to two weeks while maintaining some heavier, lower-rep work to preserve neural readiness for the platform.

Sheiko's own long coaching tenure with Russian national teams, and later work with lifters and federations outside Russia, is the primary credibility anchor for this system-level documentation; this profile treats the widely circulated numbered templates as representative of his publicly known coaching approach without claiming access to, or reproduction of, any single official unpublished coaching document.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly reported nutritional context around the Sheiko coaching system and the Russian powerlifting culture it emerged from. It is educational history, not a prescription, and the evidence here is explicitly system-level rather than a personal diet attributed to Boris Sheiko himself.

Unlike the training methodology, which is extensively documented through widely shared numbered templates, there is little translated, independently verifiable public record of a specific personal dietary system attributed directly to Sheiko. What can be documented with reasonable confidence is the broader nutritional culture surrounding Soviet and post-Soviet Russian strength-sport institutes that produced his coaching approach: a structured, weight-class-conscious eating culture common to Olympic-style sport institutes of the era, built around periodizing food intake relative to competition weigh-ins, with an emphasis on sufficient protein and carbohydrate intake to support the very high training volumes the system demands.

This general institute-level pattern — disciplined, weight-class-aware eating tied to a competition calendar rather than an aesthetic goal — is consistent with public descriptions of Soviet and Russian strength-sport training culture more broadly, but it should not be mistaken for a documented personal Sheiko diet plan, because no such detailed personal record is part of the reliable translated public record available in Western strength-sport media.

This profile is deliberately conservative for that reason: it documents the system-level nutritional culture around Sheiko-style training rather than inventing a specific meal plan that would misrepresent the actual, thinner evidence base. Readers interested in weight-class nutrition periodization should treat this as historical and cultural context rather than a step-by-step dietary programme.

More broadly, publicly available accounts of Soviet and Russian Olympic-sport nutrition science describe a systematized approach to periodizing food intake around training-cycle demands, with intake generally increased during the high-volume phases characteristic of Sheiko-style programming and adjusted downward as a lifter approaches a competition weigh-in within their declared class. This institutional approach was historically documented as being managed collaboratively between coaching staff and sport-science or medical personnel attached to national training centres, rather than left to individual athlete discretion in the way Western strength-sport nutrition culture often is. That institutional, team-based nutrition model is a genuinely documented feature of the sporting culture Sheiko's coaching career grew out of, even though it does not translate into a specific personal diet plan that can be responsibly attributed to him individually in the public record available in English-language sources.

As Sheiko's coaching influence spread internationally through translated templates and Western coaches who adopted or adapted his methodology, the nutrition conversation around "Sheiko-style" training in English-language coaching content has generally focused on supporting the very high submaximal training volume the system demands — adequate carbohydrate intake to sustain frequent moderate-load sessions, and sufficient protein to support recovery from that volume — rather than on any specific periodized diet attributed to Sheiko personally. This profile treats that Western-coaching-community framing as a reasonable general extension of the system's known training demands, while still distinguishing it clearly from a documented personal nutritional philosophy belonging to Sheiko himself, which remains outside the reliable public record available in translation.`,
  },

  "louie-simmons-conjugate-method": {
    coreTrainingRoutine: `Historical documentation note: the following reconstructs publicly documented structural principles of Louie Simmons's Conjugate Method as practiced at Westside Barbell. It is educational history describing a coaching system built over decades of Simmons's own published articles and interviews, not a prescription.

The Conjugate Method's weekly structure is unusually well documented because Simmons wrote and spoke extensively about it himself across decades of published training articles and interviews. The core weekly template consistently described across that body of work is a four-day split: Max Effort Lower, Max Effort Upper, Dynamic Effort Lower, and Dynamic Effort Upper, repeating across the week with the two modalities — maximal-effort work and speed work — trained separately rather than blended within a single session.

On Max Effort days, the publicly documented approach rotates a near-maximal exercise variation — commonly cited examples include box squats at varying heights, good mornings, rack pulls, and specialty bar variations — worked up to a genuine one-to-three repetition maximum for that specific variation, with the exercise itself deliberately rotated roughly every one to three weeks. The stated rationale, repeated across Simmons's own writing, was avoiding the nervous system's accommodation to a single repeated maximal lift, on the theory that varying the exact movement while keeping the effort maximal would continue to drive adaptation without the staleness of testing the same competition lift at true maximum every week.

This system was documented at length across decades of Simmons's own published training articles and a widely referenced book compiling Westside Barbell's methodology, through which the Conjugate Method became one of the most extensively self-documented training systems in modern strength sport — considerably more thoroughly published, in the athlete's or coach's own words, than most of the other entries in this collection. General physical preparedness work, described in this literature as a foundation supporting the two primary training days, reportedly included sled dragging, various forms of ab and lower-back-specific accessory work, and conditioning intended to accelerate recovery between sessions rather than to build a separate cardiovascular training goal.

Dynamic Effort days are the method's other defining pillar: submaximal percentages, publicly cited in the range of roughly 50-to-60 percent of a training max for squat and deadlift work and a comparable moderate range for bench press, moved with maximal intended bar speed across multiple sets of low reps (commonly two or three), frequently combined with accommodating resistance in the form of chains or elastic bands to alter the resistance curve through the lift — lighter at the bottom, heavier at the top — a signature technical element widely associated with Westside Barbell's public reputation. Box squats, used across both max- and dynamic-effort lower days in various forms, are documented as a technical teaching tool for hip-hinge patterning and posterior-chain engagement. Substantial accessory and "special exercise" work — reverse hyperextensions, glute-ham raises, and sled work among the most frequently cited — rounds out the publicly documented system, aimed at building the surrounding strength qualities that support the two primary training days.

Two custom pieces of equipment documented as central to the gym's published methodology were the reverse hyperextension machine and the glute-ham raise, both credited in Simmons's own writing as tools built specifically to address posterior-chain and lower-back weaknesses he identified as limiting factors in raw powerlifting performance, and both later became widely adopted across the broader strength-training industry well beyond Westside Barbell itself. The overall system produced a documented roster of elite raw and equipped powerlifters across multiple decades competing out of the same gym, which is part of why the Conjugate Method is treated across the sport as a genuinely tested, long-running system rather than a short-lived training fad — though this profile notes that individual lifter results within any single gym reflect selection and coaching context as well as the method itself, and should not be read as a guaranteed outcome of the system in isolation.`,
    documentedNutritionalApproach: `Historical documentation note: the following reconstructs publicly available context around nutrition within the Westside Barbell training culture associated with Louie Simmons. It is educational history, not a prescription, and the evidence here is explicitly thinner than the extensive documentation available for the Conjugate training method itself.

Simmons is documented almost entirely through his contributions to training methodology rather than nutrition; there is no widely circulated, formally published Simmons diet system comparable to the training templates described above. What exists in the public record is largely anecdotal: interview comments and gym culture references describing a straightforward, unglamorous, high-protein eating approach broadly associated with a Midwestern American strength-sport gym culture, prioritizing sufficient food to support very heavy training loads over any specific periodized macro strategy.

This profile is explicit about that evidentiary gap rather than filling it with invented specificity. Where other entries in this collection can cite repeated, cross-referenced dietary detail from decades of athlete interviews, the Conjugate Method's public record is overwhelmingly a training-methodology record. The honest historical statement is that Simmons and the Westside Barbell community are documented as prioritizing simple, protein-forward eating to support heavy lifting, without a formally published or independently verified personal diet system attributable to Simmons himself.

Readers interested in the nutritional side of powerlifting-style training are better served by looking at more thoroughly documented weight-class and periodization nutrition practices described elsewhere in this collection than by treating this entry as a source of specific dietary guidance.

What is documented, indirectly, is the physical scale of the athletes who trained successfully under this system across its decades of operation, which is broadly consistent with a food-abundant, protein-forward eating culture typical of American strength-sport gyms of the same era rather than any specifically engineered nutritional periodization. Simmons's own extensive published writing focused almost exclusively on training methodology, equipment, and biomechanics rather than nutrition, and interviewers who spoke with him across his coaching career generally did not draw out a detailed dietary philosophy in the way they did for training theory. This profile treats that absence as itself informative: the Conjugate Method's public legacy is a training-system legacy, and this entry does not manufacture a nutritional counterpart that the historical record does not actually support.

Coaches and lifters who trained under Simmons across the gym's long history have, in their own separate interviews over the years, occasionally referenced general food culture around the gym — large, simple meals and an emphasis on eating enough to support the training volume the Conjugate system demands — but these are secondary, individually variable recollections rather than a documented policy attributable to Simmons as a coach. Given that the underlying evidence for a Simmons-specific nutritional philosophy is this thin, this profile limits itself to describing the honest absence and its likely explanation (a training-methodology-first coaching career) rather than assembling secondhand gym-culture anecdotes into something that would misleadingly resemble a coherent, attributable diet system.`,
  },
};

/** Look up historical documentation bodies for a legendary-methods profile slug, if any exist. */
export function historicalDocumentationForSlug(
  slug: string,
): HistoricalDocumentationBodies | null {
  return HISTORICAL_DOCUMENTATION_BY_SLUG[slug] ?? null;
}
